# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: Little Mac calcs. straight_lunge_armor(): for each opponent hitbox, whether
#          Straight Lunge (neutral B) armor tanks it fresh, only after N stales, or never.
# Rules + sources: "Straight Lunge armor" section of docs/moveset.md (open questions are noted
#          there, see its `% research: discrepancy` lines).
# ---------------------------------------------------------------------------
from __future__ import annotations

import polars as pl

from ds.calc.modifiers import SHORT_HOP_ATTACK_MULTIPLIER, SMASH_ATTACKS, smash_full_charge_multiplier
from ds.calc.stale import min_stales

__all__ = ["SL_ARMOR_FULL_CHARGE", "SL_ARMOR_UNCHARGED", "armor_result", "straight_lunge_armor"]

# damage-based armor thresholds in base damage (1v1 multiplier scales damage + threshold alike)
# docs-source: docs/moveset.md#sl-armor-thresholds (sync-tested)
SL_ARMOR_UNCHARGED = 8.0
SL_ARMOR_FULL_CHARGE = 14.0
# grabs ignore armor (throws only hit the grabbed opponent); dodges don't hit
# docs-source: docs/moveset.md#sl-armor-modifiers (Grabs row)
_SKIPPED_CATEGORIES = ("Grabs / Throws", "Dodges / Rolls")


# docs-source: docs/moveset.md#sl-armor-modifiers (tie rule row)
def armor_result(damage: float | None, threshold: float) -> str:
    """'fresh', 'after N stales', 'never', or 'not computed' (damage unknown).

    A hit is tanked when its damage is at or below the threshold (tie rule, see docs).

    Args:
        damage: base damage of the hit (before freshness/staleness), or None if unknown.
        threshold: armor threshold, eg SL_ARMOR_UNCHARGED.
    """
    if damage is None:
        return "not computed"
    k = min_stales(damage, threshold)
    if k is None:
        return "never"
    if k == 0:
        return "fresh"
    return f"after {k} stale" + ("s" if k > 1 else "")


# docs-source: docs/moveset.md#sl-armor-modifiers (short hop attack, full charge rows)
def _variants(char_id: str, category: str, move: str, damage: float | None) -> list[tuple[str, float | None]]:
    """The normal hit plus variants frame data leaves out (short hop attack, charged smash)."""
    variants: list[tuple[str, float | None]] = [("normal", damage)]
    if damage is None:
        return variants
    if category == "Aerial Attacks":
        variants.append(("short hop attack", damage * SHORT_HOP_ATTACK_MULTIPLIER))
    if move in SMASH_ATTACKS:
        variants.append(("full charge", damage * smash_full_charge_multiplier(char_id, move)))
    return variants


def straight_lunge_armor(hitboxes: pl.DataFrame) -> pl.DataFrame:
    """Whether uncharged / fully charged Straight Lunge armor tanks each hitbox.

    Returns one row per hitbox and damage variant, with columns move, hitbox, variant, damage,
    uncharged, full_charge and raw_damage. `uncharged` / `full_charge` hold:
    - 'fresh': tanked even with the freshness bonus
    - 'after N stales': tanked once the move has been used N times in a row
    - 'never': breaks the armor even fully stale
    - 'not computed': damage isn't a plain number in frame data
    Grabs, throws and dodges are left out.

    Args:
        hitboxes: output of ds.data.hitboxes() for one character.
    """
    rows = []
    for r in hitboxes.filter(~pl.col("category").is_in(_SKIPPED_CATEGORIES)).iter_rows(named=True):
        for variant, damage in _variants(r["char_id"], r["category"], r["move"], r["damage"]):
            rows.append(
                {
                    "move": r["move"],
                    "hitbox": r["hitbox"],
                    "variant": variant,
                    "damage": None if damage is None else round(damage, 4),
                    "uncharged": armor_result(damage, SL_ARMOR_UNCHARGED),
                    "full_charge": armor_result(damage, SL_ARMOR_FULL_CHARGE),
                    "raw_damage": r["raw_damage"],
                }
            )
    schema = {
        "move": pl.String,
        "hitbox": pl.String,
        "variant": pl.String,
        "damage": pl.Float64,
        "uncharged": pl.String,
        "full_charge": pl.String,
        "raw_damage": pl.String,
    }
    return pl.DataFrame(rows, schema=schema)
