# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: Smash Ultimate damage multipliers that frame data (SmashDb / UFD) leaves out:
#          1v1 multiplier, short hop attack, full-charge smash attacks.
# Sources: see the "Straight Lunge armor" section of docs/moveset.md (Sources dropdown).
# ---------------------------------------------------------------------------
from __future__ import annotations

__all__ = [
    "ONE_V_ONE_MULTIPLIER",
    "SHORT_HOP_ATTACK_MULTIPLIER",
    "SMASH_ATTACKS",
    "SMASH_FULL_CHARGE_MULTIPLIER",
    "smash_full_charge_multiplier",
]

# damage taken in matches started with exactly 2 players and items off
# docs-source: docs/moveset.md#sl-armor-thresholds (1v1 column = threshold x this; sync-tested)
ONE_V_ONE_MULTIPLIER = 1.2
# aerials from a "short hop attack" (jump + attack together); a normal short hop aerial is 1x
# docs-source: docs/moveset.md#sl-armor-modifiers (sync-tested)
SHORT_HOP_ATTACK_MULTIPLIER = 0.85
# damage at full charge for most smash attacks
# docs-source: docs/moveset.md#sl-armor-modifiers (sync-tested)
SMASH_FULL_CHARGE_MULTIPLIER = 1.4
SMASH_ATTACKS = ("Forward Smash", "Up Smash", "Down Smash")

# smash attacks that only reach 1.2x at full charge; None = all of that character's smashes
# docs-source: docs/moveset.md#smash-charge-exceptions (sync-tested)
_SMASH_1_2X: dict[str, tuple[str, ...] | None] = {
    "bayonetta": None,
    "mega_man": ("Forward Smash",),
    "ness": ("Up Smash", "Down Smash"),
    "olimar": None,
    "villager": ("Forward Smash",),
}


def smash_full_charge_multiplier(char_id: str, move: str) -> float:
    """Full-charge damage multiplier for a smash attack (1.4x, or 1.2x for a few exceptions).

    Args:
        char_id: SmashDb character id, eg 'donkey_kong'.
        move: SmashDb move name, eg 'Forward Smash'.
    """
    if move not in SMASH_ATTACKS:
        raise ValueError(f"{move!r} is not a smash attack ({', '.join(SMASH_ATTACKS)})")
    if char_id in _SMASH_1_2X:
        moves = _SMASH_1_2X[char_id]
        if moves is None or move in moves:
            return 1.2
    return SMASH_FULL_CHARGE_MULTIPLIER
