# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: stale-move damage math for Smash Ultimate (reductors, freshness, shield staling).
#          Explained with sources in docs/mechanics/stale_moves.md; values must match that page
#          (tests/ds/calc/test_stale.py checks the reductor table against it).
# Usage: stale_factor(times_used=3) -> 0.7482; min_stales(damage=12.0, threshold=8.0) -> 5
# ---------------------------------------------------------------------------
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = [
    "FRESHNESS_BONUS",
    "QUEUE_SIZE",
    "REDUCTORS",
    "SHIELD_REDUCTOR_FACTOR",
    "min_stales",
    "stale_factor",
]

# reduction per stale-queue position (1 = most recent), Ultimate values
# ds::docs-source: docs/mechanics/stale_moves.md#stale-reductors (sync-tested)
REDUCTORS: tuple[float, ...] = (0.09, 0.08545, 0.07635, 0.0679, 0.05945, 0.05035, 0.04255, 0.03345, 0.025)
QUEUE_SIZE = len(REDUCTORS)
# damage multiplier for a move that isn't in the queue at all
# ds::docs-source: docs/mechanics/stale_moves.md#stale-multipliers (sync-tested)
FRESHNESS_BONUS = 1.05
# a queue slot filled by a shield hit only counts this fraction of its reductor
# ds::docs-source: docs/mechanics/stale_moves.md#stale-multipliers (sync-tested)
SHIELD_REDUCTOR_FACTOR = 0.85


def stale_factor(
    times_used: int = 0,
    positions: Sequence[int] = (),
    shield_positions: Sequence[int] = (),
) -> float:
    """Damage multiplier for a move given where it sits in the stale queue.

    With no positions the move is fresh (1.05). Otherwise 1 minus the sum of the reductors for
    the occupied positions (freshness no longer applies).

    Args:
        times_used: shorthand for "used this many times in a row, most recently", ie occupying
            positions 1..times_used. Combined with `positions` if both are given.
        positions: queue positions (1-9, 1 = most recent) the move occupies from hits.
        shield_positions: queue positions the move occupies from shield hits (0.85x reductor).
    """
    if not 0 <= times_used <= QUEUE_SIZE:
        raise ValueError(f"times_used must be 0-{QUEUE_SIZE}, got {times_used}")
    hit = set(range(1, times_used + 1)) | set(positions)
    shield = set(shield_positions)
    if bad := sorted(p for p in hit | shield if not 1 <= p <= QUEUE_SIZE):
        raise ValueError(f"queue positions must be 1-{QUEUE_SIZE}, got {bad}")
    if overlap := sorted(hit & shield):
        raise ValueError(f"a queue position holds one entry, both hit and shield given for {overlap}")
    if not hit and not shield:
        return FRESHNESS_BONUS
    reduction = sum(REDUCTORS[p - 1] for p in hit) + sum(REDUCTORS[p - 1] * SHIELD_REDUCTOR_FACTOR for p in shield)
    return 1 - reduction


def min_stales(damage: float, threshold: float) -> int | None:
    """Fewest consecutive recent uses needed for `damage` to drop to `threshold` or below.

    0 means it's already at or below the threshold while fresh (freshness bonus included). None
    means even a fully stale move (all 9 positions) stays above it. Consecutive most-recent
    positions are used because they have the biggest reductors, so this is the minimum.

    Args:
        damage: base damage of the hit, before freshness/staleness.
        threshold: the damage to get to or under, eg an armor threshold.
    """
    for k in range(QUEUE_SIZE + 1):
        if damage * stale_factor(times_used=k) <= threshold:
            return k
    return None
