# AUTO-GENERATED by Claude Code
from __future__ import annotations

from pathlib import Path

import polars as pl

__all__ = ["SmashDb", "init_db"]

DATA_DIR = Path(__file__).parent


class SmashDb:
    """Loads all the parquet files in data_dir as tables, named by their file name.

    This then allows to query like smash_db.sql("select * from framedata").
    """

    def __init__(self, data_dir: Path = DATA_DIR) -> None:
        self.data_dir = data_dir
        # one table per *.parquet file, named by its filename stem (eg char.parquet -> "char")
        self._tables = {p.stem: pl.scan_parquet(p) for p in sorted(data_dir.glob("*.parquet"))}
        self._ctx = pl.SQLContext(**self._tables)

    def sql(self, sql: str) -> pl.DataFrame:
        """Run a SQL query against the tables, eg smash_db.sql("select * from framedata")."""
        return self._ctx.execute(sql, eager=True)

    def tables(self) -> list[str]:
        """Table names, read off the live SQL context (not self._tables).

        So tables made/dropped through sql() (eg "create table x as select ...") are included.
        """
        return self._ctx.tables()

    def table_schema(self, table: str) -> pl.Schema:
        """{column: dtype} for one table.

        Lazy, so for a parquet table this only reads the file footer's metadata, not any rows.
        """
        return self._ctx.execute(f'SELECT * FROM "{table}"').collect_schema()

    def schema(self) -> dict[str, pl.Schema]:
        """{table: {column: dtype}} for every table, eg smash_db.schema()["char"]"""
        return {table: self.table_schema(table) for table in self.tables()}


def init_db() -> SmashDb:
    """SmashDb over the default data dir (pkgs/ds/data)."""
    return SmashDb()
