# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: split SmashDb framedata rows into one row per hitbox with a numeric damage column.
#          Eg "12.0/9.0" with whichhitbox "Early/Late" -> rows Early 12.0 and Late 9.0.
# Usage: pass framedata rows from SmashDb (ds.data.db), get one row per hitbox back.
# ---------------------------------------------------------------------------
from __future__ import annotations

import re

import polars as pl

__all__ = ["hitboxes"]

# plain per-hitbox damage, eg "10.0", "12.0/9.0", "2.7 / 3.4". Anything else (ranges like
# "10.0—27.0", "12.0(9.0)", "Grounded: 28.0% | Aerial: 25.0", "--") is kept with damage = null
_PLAIN_DAMAGE = re.compile(r"^\s*\d+(?:\.\d+)?(?:\s*/\s*\d+(?:\.\d+)?)*\s*$")


def _split(basedamage: str | None, whichhitbox: str | None) -> list[tuple[str, float | None]]:
    if basedamage is None or not _PLAIN_DAMAGE.match(basedamage):
        return [("", None)]
    damages = [float(d) for d in basedamage.split("/")]
    labels = [label.strip() for label in (whichhitbox or "").split("/")]
    if len(damages) == 1:
        return [("", damages[0])]
    if len(labels) != len(damages) or not all(labels):
        labels = [f"hitbox {i}" for i in range(1, len(damages) + 1)]
    return list(zip(labels, damages, strict=True))


def hitboxes(framedata: pl.DataFrame) -> pl.DataFrame:
    """One row per hitbox: char_id, category, move, hitbox, damage, raw_damage.

    `hitbox` is the whichhitbox label (eg 'Early'), 'hitbox N' when labels don't line up with
    the damage values, or '' for single-hitbox moves. `damage` is null when basedamage isn't a
    plain number list (ranges, conditional values, '--'); `raw_damage` keeps the original.

    Args:
        framedata: rows of SmashDb's framedata table (needs char_id, category, move,
            basedamage, whichhitbox).
    """
    rows = [
        {
            "char_id": r["char_id"],
            "category": r["category"],
            "move": r["move"],
            "hitbox": label,
            "damage": damage,
            "raw_damage": r["basedamage"],
        }
        for r in framedata.select("char_id", "category", "move", "basedamage", "whichhitbox").iter_rows(named=True)
        for label, damage in _split(r["basedamage"], r["whichhitbox"])
    ]
    schema = {
        "char_id": pl.String,
        "category": pl.String,
        "move": pl.String,
        "hitbox": pl.String,
        "damage": pl.Float64,
        "raw_damage": pl.String,
    }
    return pl.DataFrame(rows, schema=schema)
