#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# AUTO-GENERATED by GitHub Copilot
# Purpose: Run repository install tasks (sync tools, install pre-commit hook, set up git-lfs and
#          pull LFS-stored data files eg pkgs/ds/data/*.parquet).
#
# Example CLI Commands:
#   1. Run with bash:               bash .install.sh
#   2. Make executable and run:     chmod +x .install.sh && ./ .install.sh
# ---------------------------------------------------------------------------

# stop at the first failed step instead of running later steps against a half-finished setup
set -euo pipefail

uv sync
# pre-commit is in the pyproject.toml dev group (installed by `uv sync` by default)
# TODO: add install for ffmpeg (see readme)

# git-lfs: data files (eg pkgs/ds/data/*.parquet, see .gitattributes) are stored in LFS -- without it
# they're checked out as small pointer files and every read fails ("File out of specification")
if ! git lfs version >/dev/null 2>&1; then
    if command -v pacman >/dev/null 2>&1; then
        sudo pacman -S --needed --noconfirm git-lfs
    elif command -v brew >/dev/null 2>&1; then
        brew install git-lfs
    else
        echo "git-lfs not found: install it with your package manager, then rerun this script" >&2
        exit 1
    fi
fi
git lfs install
git lfs pull