#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# AUTO-GENERATED by GitHub Copilot
# Purpose: Run repository install tasks (sync tools and install pre-commit hook).
#
# Example CLI Commands:
#   1. Run with bash:               bash .install.sh
#   2. Make executable and run:     chmod +x .install.sh && ./ .install.sh
# ---------------------------------------------------------------------------

uv sync
pre-commit install
# TODO: add install for ffmpeg (see readme)