# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: pydantic-ai capability with search/read tools over the curated docs/ knowledge base.
#          Treats docs/ as the user-verified baseline and flags discrepancies against it.
# Usage: add knowledge_capability to an Agent's capabilities (wired up in ds.ai.agent).
# Design: see spec/pkgs/ds/ai/knowledge_base.md
# ---------------------------------------------------------------------------
from __future__ import annotations

import re
from dataclasses import dataclass
from functools import cache
from pathlib import Path

import yaml
from pydantic import BaseModel, Field
from pydantic_ai import ModelRetry, Tool
from pydantic_ai.capabilities import Capability

from ds.util.const import REPO_DIR

__all__ = ["DocInfo", "SearchHit", "knowledge_capability", "list_docs", "read_doc", "search_docs"]

DOCS_DIR = REPO_DIR / "docs"
# not part of the published site / knowledge base (build output, scratch, test pages)
EXCLUDED_DIRS = {"_build", "scratch", "local"}
# caps on what's handed back to the model, so a broad search/read doesn't flood its context
MAX_SEARCH_HITS = 30
MAX_READ_CHARS = 20_000

_FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")

_INSTRUCTIONS = """\
You answer Super Smash Bros. Ultimate questions. docs/ is the user's reviewed knowledge base and the baseline:
- Search docs first (search_docs with the topic plus its synonyms/shorthand; docs/glossary.md lists aliases),
  then read the relevant section. Answer from docs and cite the page as `docs/<path>.md:<line>`.
- If your general knowledge or another tool (eg SmashDb) disagrees with docs, keep the docs answer first and add a
  "Discrepancy:" note: what docs says (path:line), what the other source says, confidence in each, and a quick
  training-mode test to settle it. Never silently override docs.
- If docs doesn't cover it, still answer from general knowledge, but say it's not from docs and how confident you
  are. Be careful with exact numbers from memory, and with info that is really about Smash 4/Melee/Brawl.
- `% research:` lines in a page are provenance notes; claims marked unverified there are weaker than sourced or
  labbed ones."""


class DocInfo(BaseModel):
    """One knowledge-base page in the docs index."""

    path: str = Field(description="Repo-relative page path, eg docs/mechanics/stale_moves.md")
    title: str
    description: str = Field(description="One-line summary from the page frontmatter")
    keywords: list[str] = Field(description="Synonyms/shorthand the page covers")


class SearchHit(BaseModel):
    """One matching line from search_docs."""

    path: str = Field(description="Repo-relative page path; cite as path:line")
    line: int = Field(description="1-based line number in the file (1 for a frontmatter keyword match)")
    section: str = Field(description="Nearest heading above the line, or '(keywords)' for a keyword match")
    text: str = Field(description="The matching line (or title + description for a keyword match)")


@dataclass(frozen=True)
class _Page:
    path: str  # relative to repo root, eg docs/mechanics/stale_moves.md
    title: str
    description: str
    keywords: tuple[str, ...]
    lines: tuple[str, ...]  # full file lines, so line numbers match the file on disk
    body_start: int  # index of the first line after the frontmatter


def _parse_page(file: Path) -> _Page:
    text = file.read_text(encoding="utf-8")
    meta: dict = {}
    body_start = 0
    if m := _FRONTMATTER_RE.match(text):
        body_start = m.group(0).count("\n")
        try:
            meta = yaml.safe_load(m.group(1)) or {}
        except yaml.YAMLError:
            meta = {}
    lines = tuple(text.splitlines())
    title = meta.get("title") or next(
        (h.group(2).strip() for line in lines if (h := _HEADING_RE.match(line)) and len(h.group(1)) == 1),
        file.stem.replace("_", " ").title(),
    )
    return _Page(
        path=file.relative_to(REPO_DIR).as_posix(),
        title=str(title),
        description=str(meta.get("description") or ""),
        keywords=tuple(str(k) for k in meta.get("keywords") or ()),
        lines=lines,
        body_start=body_start,
    )


@cache
def _pages() -> tuple[_Page, ...]:
    files = (
        f for f in sorted(DOCS_DIR.rglob("*.md")) if not EXCLUDED_DIRS.intersection(f.relative_to(DOCS_DIR).parts[:-1])
    )
    return tuple(_parse_page(f) for f in files)


def _page(path: str) -> _Page:
    rel = path.strip().removeprefix("./")
    if not rel.startswith("docs/"):
        rel = f"docs/{rel}"
    if not rel.endswith(".md"):
        rel += ".md"
    for page in _pages():
        if page.path == rel:
            return page
    raise ModelRetry(f"No docs page {path!r}. Use list_docs or search_docs to find valid paths.")


def _heading_at(page: _Page, line_idx: int) -> str:
    """Nearest heading at or above a line, so a search hit shows which section it's in."""
    for line in reversed(page.lines[: line_idx + 1]):
        if h := _HEADING_RE.match(line):
            return h.group(2).strip()
    return ""


def _numbered(lines: list[str], start: int) -> str:
    """Prefix each line with its 1-based file line number, so answers can cite path:line."""
    return "\n".join(f"{start + i + 1:>4}| {line}" for i, line in enumerate(lines))


def list_docs(folder: str = "") -> list[DocInfo]:
    """Index of knowledge-base pages: path, title, description and keywords (synonyms).

    Start here to see what docs cover, then use read_doc on the relevant page.

    Args:
        folder: only list pages under this docs/ subfolder, eg 'mechanics' or 'matchups'.
            Empty lists all.
    """
    prefix = f"docs/{folder.strip().strip('/')}/" if folder.strip() else "docs/"
    return [
        DocInfo(path=p.path, title=p.title, description=p.description, keywords=list(p.keywords))
        for p in _pages()
        if p.path.startswith(prefix)
    ]


def search_docs(terms: list[str]) -> list[SearchHit]:
    """Case-insensitive search of docs/ pages for any of the given terms.

    Pass the topic plus its synonyms and shorthand (eg ['stale', 'staling', 'freshness'] or
    ['nair', 'neutral air']). Hits are ranked by how many distinct terms a line matches; a page
    whose frontmatter keywords match is also returned. Returns at most 30 hits.

    Args:
        terms: words or phrases to look for; a line matches if it contains any of them.
    """
    needles = [t.strip().lower() for t in terms if t.strip()]
    if not needles:
        raise ModelRetry("Pass at least one non-empty search term.")
    hits: list[tuple[int, SearchHit]] = []
    for page in _pages():
        kw = " ".join(page.keywords).lower()
        if kw_matches := sum(n in kw for n in needles):
            # keyword hits rank above line hits: the page is explicitly about the topic
            hit = SearchHit(path=page.path, line=1, section="(keywords)", text=f"{page.title}: {page.description}")
            hits.append((kw_matches + len(needles), hit))
        for i, line in enumerate(page.lines[page.body_start :], start=page.body_start):
            low = line.lower()
            if score := sum(n in low for n in needles):
                hit = SearchHit(path=page.path, line=i + 1, section=_heading_at(page, i), text=line.strip()[:300])
                hits.append((score, hit))
    hits.sort(key=lambda h: -h[0])  # stable sort keeps file order among equal scores
    return [h for _, h in hits[:MAX_SEARCH_HITS]]


def read_doc(path: str, section: str = "") -> str:
    """Read a docs page (or one section of it) with line numbers for citing as path:line.

    Args:
        path: page path from list_docs/search_docs, eg 'docs/mechanics/stale_moves.md'
            (the 'docs/' prefix and '.md' suffix are optional).
        section: heading text (case-insensitive substring) to read just that section and its
            subsections. Empty reads the whole page (truncated at 20k characters).
    """
    page = _page(path)
    lines = list(page.lines)
    start, end = 0, len(lines)
    if section.strip():
        want = section.strip().lower()
        for i, line in enumerate(lines):
            if (h := _HEADING_RE.match(line)) and want in h.group(2).lower():
                level = len(h.group(1))
                start = i
                end = next(
                    (
                        j
                        for j in range(i + 1, len(lines))
                        if (h2 := _HEADING_RE.match(lines[j])) and len(h2.group(1)) <= level
                    ),
                    len(lines),
                )
                break
        else:
            headings = [h.group(2) for line in lines if (h := _HEADING_RE.match(line))]
            raise ModelRetry(f"No section {section!r} in {page.path}. Headings are: {headings}")
    out = _numbered(lines[start:end], start)
    if len(out) > MAX_READ_CHARS:
        out = out[:MAX_READ_CHARS] + "\n... (truncated; read a specific section)"
    return f"{page.path}\n{out}"


knowledge_capability = Capability(
    id="smash_knowledge",
    description="Smash Ultimate knowledge base (docs/): mechanics, matchups, tech, stages, glossary.",
    instructions=_INSTRUCTIONS,
    # return schemas tell the model what each result field means (see DocInfo / SearchHit)
    tools=[
        Tool(list_docs, include_return_schema=True),
        Tool(search_docs, include_return_schema=True),
        read_doc,
    ],
    # deferred: instructions + tool defs only enter context once a Smash question comes up
    defer_loading=True,
)
