# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: pydantic-ai capability for Little Mac questions, eg "which of DK's moves can
#          neutral B armor through?" (wraps ds.calc.little_mac + SmashDb frame data).
# Usage: add little_mac_capability to an Agent's capabilities (wired up in ds.ai.agent).
# ---------------------------------------------------------------------------
# TODO: need to have information on charged vs not charged for full SL break
# https://docs.google.com/spreadsheets/d/1kpnXzwdspS1kR-rQWFm0l2GejtRfR_tmc-U6IA8JwRU/edit?gid=909113482#gid=909113482
from __future__ import annotations

from functools import cache

import polars as pl
from pydantic_ai import Tool
from pydantic_ai.capabilities import Capability

from ds.ai.smashdb import resolve_char_id
from ds.ai.table import TableResult
from ds.calc.little_mac import SL_ARMOR_FULL_CHARGE, SL_ARMOR_UNCHARGED
from ds.calc.little_mac import straight_lunge_armor as _straight_lunge_armor
from ds.data.db import SmashDb, init_db
from ds.data.hitboxes import hitboxes

__all__ = ["little_mac_capability", "straight_lunge_armor"]

SL_ARMOR_DOC = "docs/moveset.md"  # "Straight Lunge armor" section

# docs-source: docs/moveset.md#sl-armor (instructions summarize it; numbers from ds.calc)

_INSTRUCTIONS = f"""\
For whether Little Mac's neutral B (Straight Lunge, SL) armor tanks an opponent's moves, call straight_lunge_armor
and present its table (group by move; keep the hitbox and variant). Explain the columns: uncharged SL
({SL_ARMOR_UNCHARGED:g}% armor) vs fully charged SL ({SL_ARMOR_FULL_CHARGE:g}%), where "fresh" means tanked even
fresh, "after N stales" means the opponent must have used that move N times in a row, and "never" means it always
breaks the armor. Only uncharged and full charge are known; partial charge is somewhere in between (not labbed
yet). The result is the same in 1v1 and other formats, because the 1v1 multiplier scales the damage and the armor
alike, so don't apply 1.2x here. Rules and sources: the "Straight Lunge armor" section of {SL_ARMOR_DOC}. Open
data questions are listed in docs/scratch/discrepancies.md (search it for the move or character); mention the
D-ID when a row depends on one."""


@cache
def _db() -> SmashDb:
    return init_db()


def straight_lunge_armor(character: str) -> TableResult:
    """Whether Little Mac's Straight Lunge (neutral B) armor tanks each of a character's hits.

    One row per hitbox and variant ('normal', 'short hop attack' for aerials, 'full charge' for
    smash attacks). Columns `uncharged` / `full_charge` are 'fresh', 'after N stales', 'never'
    or 'not computed' (damage isn't a plain number in frame data). Grabs, throws and dodges are
    left out.

    Args:
        character: the opponent, as a character id or name, eg 'donkey_kong' or 'Donkey Kong'.
    """
    char_id = resolve_char_id(character)
    framedata = _db().sql("select * from framedata").filter(pl.col("char_id") == char_id)
    return TableResult.from_df(_straight_lunge_armor(hitboxes(framedata)).drop("raw_damage"))


little_mac_capability = Capability(
    id="little_mac",
    description="Little Mac calculators: whether Straight Lunge (neutral B) armor tanks an opponent's moves.",
    instructions=_INSTRUCTIONS,
    tools=[Tool(straight_lunge_armor, include_return_schema=True)],
    # deferred: instructions + tool defs only enter context once a Little Mac question comes up
    defer_loading=True,
)
