# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: pydantic-ai capability with general Smash Ultimate mechanics calcs, starting with
#          stale-move damage (wraps ds.calc.stale). Explained in docs/mechanics/stale_moves.md
# Usage: add mechanics_capability to an Agent's capabilities (wired up in ds.ai.agent).
# ---------------------------------------------------------------------------
from __future__ import annotations

from pydantic import BaseModel, Field
from pydantic_ai import ModelRetry, Tool
from pydantic_ai.capabilities import Capability

from ds.calc.modifiers import ONE_V_ONE_MULTIPLIER
from ds.calc.stale import FRESHNESS_BONUS, REDUCTORS, SHIELD_REDUCTOR_FACTOR, stale_factor

__all__ = ["StaleDamage", "mechanics_capability", "stale_damage"]

# ds::docs-source: docs/mechanics/stale_moves.md (tool output cites it; numbers from ds.calc)
STALE_DOC = "docs/mechanics/stale_moves.md"

_INSTRUCTIONS = f"""\
Use stale_damage for any stale-move damage number instead of doing the arithmetic yourself. For how staling
works (queue, what enters it, refreshing), read {STALE_DOC} with the docs tools and cite it."""


class StaleDamage(BaseModel):
    """Damage of a move at a given staleness."""

    base_damage: float = Field(description="Listed (frame data) damage the calc started from")
    factor: float = Field(description="Staleness multiplier: 1.05 fresh, below 1 when stale")
    damage: float = Field(description="base_damage x factor (damage outside 1v1)")
    damage_1v1: float = Field(description="damage x the 1v1 multiplier (what the opponent takes in 1v1)")
    breakdown: str = Field(description="How the factor was computed, for showing the user")
    doc: str = Field(description="Docs page explaining the mechanic, to cite or read for more detail")


def stale_damage(
    base_damage: float,
    times_used: int = 0,
    positions: list[int] | None = None,
    shield_positions: list[int] | None = None,
) -> StaleDamage:
    """Damage of a move after staling (or fresh, with the freshness bonus).

    Args:
        base_damage: the move's listed damage from frame data, eg 12.0.
        times_used: times the move connected in a row most recently (fills queue positions
            1..times_used), eg 3. 0 with no positions = fresh.
        positions: exact queue positions (1-9, 1 = most recent) the move occupies from hits,
            eg [1, 2, 6].
        shield_positions: queue positions it occupies from hitting a shield, eg [1].
    """
    try:
        factor = stale_factor(times_used, positions or (), shield_positions or ())
    except ValueError as e:
        raise ModelRetry(str(e)) from e
    hit = sorted(set(range(1, times_used + 1)) | set(positions or ()))
    shield = sorted(set(shield_positions or ()))
    if not hit and not shield:
        breakdown = f"fresh (not in the queue): freshness bonus x{FRESHNESS_BONUS}"
    else:
        parts = [f"pos {p}: {REDUCTORS[p - 1]}" for p in hit]
        parts += [f"pos {p} (shield): {REDUCTORS[p - 1]} x {SHIELD_REDUCTOR_FACTOR}" for p in shield]
        breakdown = f"1 - ({' + '.join(parts)}) = {factor:.4f}"
    damage = base_damage * factor
    return StaleDamage(
        base_damage=base_damage,
        factor=round(factor, 5),
        damage=round(damage, 4),
        damage_1v1=round(damage * ONE_V_ONE_MULTIPLIER, 4),
        breakdown=breakdown,
        doc=STALE_DOC,
    )


mechanics_capability = Capability(
    id="smash_mechanics",
    description="Smash Ultimate mechanics calculators: stale-move damage.",
    instructions=_INSTRUCTIONS,
    tools=[Tool(stale_damage, include_return_schema=True)],
    # deferred: instructions + tool defs only enter context once a relevant question comes up
    defer_loading=True,
)
