# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: pydantic-ai capability giving an agent tools to answer Smash Ultimate questions
#          from SmashDb (pkgs/ds/data/*.parquet), eg a character's frame data for a move.
# Usage: Agent(..., capabilities=[smashdb_capability]); see ds.ai.agent for the wired-up agent.
# ---------------------------------------------------------------------------
# TODO: see if want SQL syntax rather than polars syntax as preferred so can more easily read
# TODO: asking "for smash ultimate, could you show me ranked list of nair by startup" claude
# had way of writing better compact in table,
# for example see https://discord.com/channels/@me/1460291571730878782/1554604391846117517
from __future__ import annotations

import re
from functools import cache

import polars as pl
from pydantic_ai import ModelRetry
from pydantic_ai.capabilities import Capability

from ds.data.db import SmashDb, init_db

__all__ = ["find_character", "get_move_framedata", "list_moves", "query_smashdb", "smashdb_capability"]

# cap on rows handed back to the model, so a broad query doesn't flood its context
MAX_ROWS = 200

# common player shorthand -> the move-name wording used in framedata.move
MOVE_ALIASES = {
    "nair": "Neutral Air",
    "fair": "Forward Air",
    "bair": "Back Air",
    "uair": "Up Air",
    "dair": "Down Air",
    "zair": "Z Air",
    "ftilt": "Forward Tilt",
    "utilt": "Up Tilt",
    "dtilt": "Down Tilt",
    "fsmash": "Forward Smash",
    "usmash": "Up Smash",
    "dsmash": "Down Smash",
    "da": "Dash Attack",
    "nb": "Neutral B",
    "sb": "Side B",
    "ub": "Up B",
    "db": "Down B",
    "fthrow": "Forward Throw",
    "bthrow": "Backward Throw",
    "uthrow": "Up Throw",
    "dthrow": "Down Throw",
}


_INSTRUCTIONS = """\
You answer Super Smash Bros. Ultimate questions using SmashDb (frame data scraped from
ultimateframedata.com). Always ground answers in tool results rather than memory; if the data
doesn't have it, say so.
Prefer get_move_framedata / list_moves / find_character; use query_smashdb for cross-character or
aggregate questions.
Frame data values are strings: '--' means not applicable, 'a/b' lists per-hitbox values (see
whichhitbox), and activeframes like '5—7' are frame ranges. 'advantage' is frame advantage on
shield (negative = punishable).

SmashDb tables (framedata.char_id -> char.id):
{schema}"""


@cache
def _db() -> SmashDb:
    return init_db()


def _char_df() -> pl.DataFrame:
    return _db().sql("select * from char")


def _framedata_df() -> pl.DataFrame:
    return _db().sql("select * from framedata")


def _resolve_char_id(character: str) -> str:
    """Map a user-given character (id, display name, or partial name) to one char.id."""
    chars = _char_df()
    q = character.strip().lower()
    exact = chars.filter((pl.col("id") == q.replace(" ", "_")) | (pl.col("name").str.to_lowercase() == q))
    if exact.height == 1:
        return exact["id"][0]
    partial = chars.filter(
        pl.col("id").str.contains(q.replace(" ", "_"), literal=True)
        | pl.col("name").str.to_lowercase().str.contains(q, literal=True)
    )
    if partial.height == 1:
        return partial["id"][0]
    if partial.height == 0:
        raise ModelRetry(f"No character matches {character!r}. Use find_character to look up valid ids.")
    raise ModelRetry(f"{character!r} is ambiguous, pick one of: {partial['id'].to_list()}")


def _normalize_move(move: str) -> str:
    """Expand player shorthand (eg 'fair', 'up b') to the site's move wording."""
    m = move.strip()
    key = re.sub(r"[\s\-]", "", m.lower())
    return MOVE_ALIASES.get(key, m)


def find_character(query: str = "") -> list[dict]:
    """Search the character roster by id or display name (case-insensitive substring).

    Args:
        query: part of a character's id or name, eg 'mac' or 'donkey'. Empty returns all.
    """
    q = query.strip().lower()
    chars = _char_df()
    if q:
        chars = chars.filter(
            pl.col("id").str.contains(q.replace(" ", "_"), literal=True)
            | pl.col("name").str.to_lowercase().str.contains(q, literal=True)
        )
    return chars.to_dicts()


def list_moves(character: str) -> list[dict]:
    """List every move (with its category) that has frame data for a character.

    Args:
        character: character id or name, eg 'mario', 'Little Mac'.
    """
    char_id = _resolve_char_id(character)
    return _framedata_df().filter(pl.col("char_id") == char_id).select("category", "move").to_dicts()


def get_move_framedata(character: str, move: str) -> list[dict]:
    """Get frame data (startup, active frames, on-shield advantage, damage...) for a move.

    Matches the move name exactly first, then falls back to a case-insensitive substring
    match, so 'Up B' returns every Up B variant. Shorthand like 'fair', 'dtilt', 'nb' works.

    Args:
        character: character id or name, eg 'mario', 'Little Mac'.
        move: move name, eg 'Forward Air', 'fair', 'Jab 1', 'Up B'.
    """
    char_id = _resolve_char_id(character)
    moves = _framedata_df().filter(pl.col("char_id") == char_id)
    name = _normalize_move(move)
    exact = moves.filter(pl.col("move").str.to_lowercase() == name.lower())
    rows = exact
    if rows.height == 0:
        rows = moves.filter(pl.col("move").str.to_lowercase().str.contains(name.lower(), literal=True))
    if rows.height == 0:
        raise ModelRetry(f"No move matching {move!r} for {char_id}. Moves are: {moves['move'].to_list()}")
    # drop all-null columns (eg landinglag on ground moves) to keep the answer focused
    return rows.select([c for c in rows.columns if rows[c].null_count() < rows.height]).to_dicts()


def query_smashdb(sql: str) -> list[dict]:
    """Run a read-only SQL SELECT against SmashDb for questions other tools can't answer.

    Eg ranking or comparing moves across characters. Tables are described in the instructions.
    Frame-data columns are strings with values like '--', '10/17', '4 (Gold: 3)', so use
    TRY_CAST(startup AS INT) (null when not a plain number) for numeric comparisons.
    Returns at most 200 rows.

    Args:
        sql: a single SELECT (or WITH ... SELECT) statement.
    """
    stmt = sql.strip().rstrip(";")
    if not re.match(r"(?is)^\s*(select|with)\b", stmt) or ";" in stmt:
        raise ModelRetry("Only a single read-only SELECT/WITH statement is allowed.")
    try:
        df = _db().sql(stmt)
    except Exception as e:  # polars raises several SQL/compute error types; hand them all back to the model
        raise ModelRetry(f"SQL error: {e}") from e
    return df.head(MAX_ROWS).to_dicts()


def _instructions() -> str:
    schema = "\n".join(
        f"- {table}: " + ", ".join(f"{col} ({dtype})" for col, dtype in cols.items())
        for table, cols in _db().schema().items()
    )
    return _INSTRUCTIONS.format(schema=schema)


smashdb_capability = Capability(
    id="smashdb",
    description="Smash Ultimate database: character roster and per-move frame data.",
    instructions=_instructions,
    tools=[find_character, list_moves, get_move_framedata, query_smashdb],
    # deferred: schema + tool defs only enter context once a Smash question comes up
    defer_loading=True,
)
