# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: pydantic-ai capability for a player's supermajor.gg stats by tag, eg "what does
#          Lukedub play and which stages do they pick?" (wraps ds.data.raw.supermajor).
# Usage: add supermajor_capability to an Agent's capabilities (wired up in ds.ai.agent).
# ---------------------------------------------------------------------------
from __future__ import annotations

from typing import Literal

import httpx2
from pydantic_ai import ModelRetry, Tool
from pydantic_ai.capabilities import Capability

from ds.data.raw.supermajor import (
    ALL_TIME,
    LAST_6_MONTHS,
    PlayerMatch,
    PlayerUsage,
    player_usage,
    search_players,
)

__all__ = ["find_players", "get_player_usage", "supermajor_capability"]

# cap on search results handed back to the model
MAX_PLAYERS = 25

_PERIODS = {"last_6_months": LAST_6_MONTHS, "all_time": ALL_TIME}

_INSTRUCTIONS = """\
For a competitive Smash Ultimate player's character and stage usage, use get_player_usage with their
tag (eg 'Lukedub'), supermajor.gg player id (eg 'S4734338') or player page url. Data comes from
supermajor.gg (tournament sets from start.gg), not from docs/.
- Tags aren't unique. Check `lookup`: `match_type` is tag_exact (same case), tag_any_case, player_id
  or url; `tied_matches` > 1 means several players share the tag and the one with the most events was
  picked. Say who was picked (tag, region, events) and, on a tie, offer find_players to choose another,
  then call get_player_usage with that player's id.
- `characters` covers the requested period (last 6 months by default). Stage stats (`starters` =
  game 1 stages, `counters` = counterpick stages) aren't filtered by period and the site doesn't
  say what time range they cover, so don't call them all-time or recent; just say unfiltered.
- usage_pct is 0-100 (share of games with character/stage data). Mention game counts, since small
  samples (eg 2 games) mean little. Empty lists mean the site has no data for them.
- Facts only: the user is prepping for opponents and doesn't want to judge how good they are. Don't
  bring up win rates, records, rankings, seeds or placements, even from memory or other sources,
  unless the user asks for them directly."""


def find_players(tag: str) -> list[PlayerMatch]:
    """Search supermajor.gg Smash Ultimate players by tag, most events first.

    Matches substrings in any case, so 'luke' also finds 'Lukedub'. Use it to pick among
    players sharing a tag, then pass the chosen player_id to get_player_usage.

    Args:
        tag: player tag or part of one, eg 'Luke'.
    """
    try:
        return search_players(tag)[:MAX_PLAYERS]
    except ValueError as e:  # missing search key
        raise ModelRetry(f"{e}. Ask the user for the player's id or url.") from e


def get_player_usage(
    player: str,
    period: Literal["last_6_months", "all_time"] = "last_6_months",
) -> PlayerUsage:
    """Get a player's character, starter-stage and counterpick-stage usage from supermajor.gg.

    Args:
        player: a tag (eg 'Lukedub'), a supermajor.gg player id (eg 'S4734338') or a player
            page url. For a shared tag, the player with the most events is picked
            (see `lookup`).
        period: character-usage period, 'last_6_months' or 'all_time'. Stage stats ignore it.
    """
    try:
        return player_usage(player, _PERIODS[period])
    except ValueError as e:  # no player with that tag / missing search key / page format changed
        hint = "Try find_players to look up the tag, or ask the user for an id or url."
        raise ModelRetry(f"{e}. {hint}") from e
    except httpx2.HTTPStatusError as e:
        raise ModelRetry(f"supermajor.gg returned {e.response.status_code} for {player!r}.") from e


supermajor_capability = Capability(
    id="supermajor",
    description="supermajor.gg player stats by tag: characters played, starter/counterpick stages.",
    instructions=_INSTRUCTIONS,
    # fixed-shape results -> pydantic models (see .agents/instructions/pkgs.md, pydantic-ai)
    tools=[
        Tool(find_players, include_return_schema=True),
        Tool(get_player_usage, include_return_schema=True),
    ],
    # deferred: instructions + tool defs only enter context once a player question comes up
    defer_loading=True,
)
