# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: TableResult, the return type for tabular pydantic-ai tool output. The model reads
#          compact CSV (~1/3 the tokens of list[dict]); Python rebuilds it with .to_df().
# Usage: return TableResult.from_df(df) from a tool. tables_from_messages(msgs) pulls every
#        table out of an agent run (live objects or messages loaded back from JSON).
# ---------------------------------------------------------------------------
from __future__ import annotations

import io
from typing import TYPE_CHECKING

import polars as pl
from pydantic import BaseModel, Field
from pydantic_ai.messages import ToolReturnPart

if TYPE_CHECKING:
    from collections.abc import Sequence

    from pydantic_ai.messages import ModelMessage

__all__ = ["TableResult", "tables_from_messages"]


def _dtype_from_name(name: str) -> pl.DataType | None:
    """Map str(dtype) (eg 'Int64') back to a polars dtype; None for complex ones (Datetime)."""
    dtype = getattr(pl, name, None) if name.isidentifier() else None
    return dtype if isinstance(dtype, type) and issubclass(dtype, pl.DataType) else None


class TableResult(BaseModel):
    """Tabular tool output: CSV for the model plus dtypes to rebuild the DataFrame."""

    rows: int = Field(description="Number of rows included in csv")
    total_rows: int = Field(description="Rows the query produced before truncation")
    truncated: bool = Field(description="True when only the first `rows` of `total_rows` are included")
    dtypes: dict[str, str] = Field(description="Column name -> polars dtype, in column order")
    csv: str = Field(description="The rows as CSV with a header line; an empty cell means null")

    @classmethod
    def from_df(cls, df: pl.DataFrame, max_rows: int | None = None) -> TableResult:
        """Build from a DataFrame, keeping at most max_rows rows (None keeps all)."""
        shown = df if max_rows is None else df.head(max_rows)
        return cls(
            rows=shown.height,
            total_rows=df.height,
            truncated=shown.height < df.height,
            dtypes={col: str(dtype) for col, dtype in shown.schema.items()},
            csv=shown.write_csv(),
        )

    def to_df(self) -> pl.DataFrame:
        """Rebuild the DataFrame with its original dtypes (complex ones are inferred).

        Note CSV can't tell an empty string from null, so empty strings come back as null.
        """
        if not self.dtypes:
            return pl.DataFrame()
        overrides = {col: dtype for col, name in self.dtypes.items() if (dtype := _dtype_from_name(name))}
        return pl.read_csv(io.StringIO(self.csv), schema_overrides=overrides)


def tables_from_messages(
    messages: Sequence[ModelMessage], tool_name: str | None = None
) -> list[tuple[str, TableResult]]:
    """Every (tool name, TableResult) returned by tools in an agent run, in call order.

    Works on live run messages (content is the TableResult object) and on messages loaded back
    from JSON (content is a plain dict). Eg:
        for name, table in tables_from_messages(result.all_messages()):
            df = table.to_df()

    Args:
        messages: agent run messages, eg result.all_messages().
        tool_name: only return tables from this tool, eg 'query_smashdb'.
    """
    tables: list[tuple[str, TableResult]] = []
    for message in messages:
        for part in message.parts:
            if not isinstance(part, ToolReturnPart) or (tool_name and part.tool_name != tool_name):
                continue
            content = part.content
            if isinstance(content, dict) and {"csv", "dtypes"} <= content.keys():
                content = TableResult.model_validate(content)
            if isinstance(content, TableResult):
                tables.append((part.tool_name, content))
    return tables
