# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: offline tests for ds.data.raw.supermajor's page parsing (synthetic Next.js payload).
# Usage: uv run pytest tests/ds/data
# ---------------------------------------------------------------------------
from __future__ import annotations

import copy
import json
import re

import pytest
from ds.data.raw.supermajor import (
    ALL_TIME,
    LAST_6_MONTHS,
    PlayerMatch,
    PlayerUsage,
    parse_player_usage,
    pick_player,
    resolve_player,
)


def _stage(sid: str, name: str, short: str, played: int, rate: float) -> dict:
    return {"stage_id": sid, "stage_name": name, "short_stage_name": short, "times_played": played, "usage_rate": rate}


def _stage_ctx(*stages: dict, games: int) -> dict:
    return {
        "stages": {s["stage_id"]: s for s in stages},
        "order": [s["stage_id"] for s in stages],
        "metadata": {"num_games_with_stage_data": games},
    }


def _event(start: str, characters: list[str]) -> dict:
    """One `recent_form` row, with the result fields we deliberately drop"""
    return {
        "event_info": {
            "start_date": f"{start}T19:00:00",
            "tournament_name": f"Weekly {start}",
            "event_name": "Singles",
            "online": True,
            "num_entrants": 40,
        },
        "entrant_info": {"characters": characters, "seed": 3, "placement": 1, "game_wins": 9, "game_losses": 1},
    }


_PS2 = _stage("A378", "Pokemon Stadium 2", "PS2", 3, 0.75)
_BF = _stage("A311", "Battlefield", "BF", 1, 0.25)

_DATA = {
    "character_info_lookup": {
        "A1297": {"character_id": "A1297", "sport": "ultimate", "name": "Little Mac"},
        "A1299": {"character_id": "A1299", "sport": "ultimate", "name": "Lucas"},
    },
    "characters": {
        "contexts": {
            LAST_6_MONTHS: {
                "characters": {
                    "A1297": {"usage_rate": 0.75, "num_games": 3, "num_wins": 2, "num_losses": 1, "winrate": 2 / 3},
                    "A1299": {"usage_rate": 0.25, "num_games": 1, "num_wins": 0, "num_losses": 1, "winrate": 0.0},
                },
                "order": ["A1297", "A1299"],
            },
            ALL_TIME: {
                "characters": {"A1299": {"usage_rate": 1.0, "num_games": 10}},
                "order": ["A1299"],
                "metadata": {"num_games_with_character_data": 10},
            },
        }
    },
    "recent_form": {
        "contexts": {
            "Last 10 Events": {
                "placements": [
                    _event("2026-09-01", ["A1299", "A1297"]),
                    _event("2026-10-01", ["A1297"]),
                    _event("2026-08-01", []),
                ]
            }
        }
    },
    "stages": {
        "contexts": {
            "all": _stage_ctx(_PS2, _BF, games=4),
            "starters": _stage_ctx(_PS2, _BF, games=4),
            "counters": _stage_ctx(games=0),
        }
    },
}


def _page(data: dict) -> str:
    """Wrap `data` like Next.js does: a JSON string split across `self.__next_f.push` chunks"""
    text = json.dumps(data)
    half = len(text) // 2
    pushes = "".join(
        f"<script>self.__next_f.push([1,{json.dumps(chunk)}])</script>" for chunk in (text[:half], text[half:])
    )
    return f"<html><body>{pushes}</body></html>"


def test_characters_prefer_last_6_months() -> None:
    usage = parse_player_usage(_page(_DATA))
    assert (usage.characters.window, usage.characters_fallback) == ("last_6_months", False)
    assert [(c.character, c.usage_pct, c.count) for c in usage.characters.characters] == [
        ("Little Mac", 75.0, 3),
        ("Lucas", 25.0, 1),
    ]
    assert (usage.characters.unit, usage.characters.total) == ("games", 4)  # no metadata -> sum of counts
    assert [(c.character, c.count) for c in usage.all_time.characters] == [("Lucas", 10)]
    assert usage.all_time.total == 10


def test_characters_fall_back_to_all_time() -> None:
    data = copy.deepcopy(_DATA)
    data["characters"]["contexts"][LAST_6_MONTHS] = {"characters": {}, "order": []}
    usage = parse_player_usage(_page(data))
    assert (usage.characters.window, usage.characters_fallback) == ("all_time", True)
    assert [c.character for c in usage.characters.characters] == ["Lucas"]
    dumped = usage.model_dump()  # computed fields are serialized for the agent / --json
    assert (dumped["characters"]["window"], dumped["characters_fallback"]) == ("all_time", True)


def test_missing_window_counts_as_no_data() -> None:
    data = copy.deepcopy(_DATA)
    del data["characters"]["contexts"][LAST_6_MONTHS]
    usage = parse_player_usage(_page(data))
    assert (usage.last_6_months.total, usage.characters_fallback) == (0, True)


def test_stages() -> None:
    usage = parse_player_usage(_page(_DATA))
    assert usage.starters.games == 4
    assert [(s.short_name, s.usage_pct) for s in usage.starters.stages] == [("PS2", 75.0), ("BF", 25.0)]
    assert usage.counters.stages == []


def test_last_10_events() -> None:
    recent = parse_player_usage(_page(_DATA)).last_10_events
    assert [e.date.isoformat() for e in recent.events] == ["2026-10-01", "2026-09-01", "2026-08-01"]
    assert (recent.first_date.isoformat(), recent.last_date.isoformat()) == ("2026-08-01", "2026-10-01")
    assert recent.events[1].characters == ["Lucas", "Little Mac"]
    stats = recent.characters  # same CharacterStats shape as the date windows
    assert (stats.window, stats.unit, stats.total) == ("last_10_events", "events", 2)  # [] event has no data
    rows = [(c.character, c.count, c.usage_pct, c.main_count) for c in stats.characters]
    assert rows == [("Little Mac", 2, 100.0, 1), ("Lucas", 1, 50.0, 1)]


def test_missing_recent_form_is_empty() -> None:
    data = copy.deepcopy(_DATA)
    del data["recent_form"]
    recent = parse_player_usage(_page(data)).last_10_events
    assert (recent.events, recent.characters.characters, recent.first_date) == ([], [], None)


def test_resolve_player() -> None:
    by_id = resolve_player("S2884234")
    assert (by_id.match_type, by_id.url.endswith("?id=S2884234")) == ("player_id", True)
    url = "https://www.supermajor.gg/ultimate/player/DeLulu?id=S4734338"
    assert (resolve_player(url).match_type, resolve_player(url).url) == ("url", url)


def test_pick_player_prefers_exact_case_then_most_events() -> None:
    matches = [
        PlayerMatch(player_id="S1", tag="Luke", num_events=167),
        PlayerMatch(player_id="S2", tag="Luke", num_events=75),
        PlayerMatch(player_id="S3", tag="luke", num_events=500),
        PlayerMatch(player_id="S4", tag="Lukedub", num_events=1),
    ]
    exact = pick_player("Luke", matches)
    assert (exact.match_type, exact.player.player_id, exact.tied_matches) == ("tag_exact", "S1", 2)
    any_case = pick_player("LUKE", matches)
    assert (any_case.match_type, any_case.player.player_id, any_case.tied_matches) == ("tag_any_case", "S3", 3)
    assert any_case.search_results == 4
    with pytest.raises(ValueError, match="similar tags"):
        pick_player("Lu", matches)


def _field_names(model: type) -> set[str]:
    """Every field name in a pydantic model, including nested models (eg list[StageUsage])"""
    names = set()
    for name, info in model.model_fields.items():
        names.add(name)
        for arg in (info.annotation, *getattr(info.annotation, "__args__", ())):
            if isinstance(arg, type) and hasattr(arg, "model_fields"):
                names |= _field_names(arg)
    return names


def test_no_skill_signals() -> None:
    """Facts only by design (see Site notes): no win/loss/ranking/placement fields"""
    names = _field_names(PlayerUsage) | _field_names(PlayerMatch)
    assert {"usage_pct", "short_name", "num_events"} <= names  # nested models are walked
    # whole words of the snake_case name, so eg `window` isn't mistaken for a win stat
    banned = re.compile(r"(^|_)(wins?|winrate|loss(es)?|rank(ing)?s?|seeds?|placements?)(_|$)")
    assert not [n for n in names if banned.search(n)]
