# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: tests for ds.data.hitboxes (SmashDb basedamage strings -> per-hitbox rows).
# Usage: uv run pytest tests/ds/data
# ---------------------------------------------------------------------------
from __future__ import annotations

import polars as pl
from ds.data.hitboxes import hitboxes


def _framedata(basedamage: str | None, whichhitbox: str | None) -> pl.DataFrame:
    return pl.DataFrame(
        {
            "char_id": ["donkey_kong"],
            "category": ["Ground Attacks"],
            "move": ["Test"],
            "basedamage": [basedamage],
            "whichhitbox": [whichhitbox],
        }
    )


def test_labelled_hitboxes() -> None:
    out = hitboxes(_framedata("12.0/9.0", "Early/Late"))
    assert out.select("hitbox", "damage").rows() == [("Early", 12.0), ("Late", 9.0)]


def test_unlabelled_hitboxes_get_numbered() -> None:
    out = hitboxes(_framedata("16.0/13.0", "--"))
    assert out["hitbox"].to_list() == ["hitbox 1", "hitbox 2"]


def test_single_and_spaced_values() -> None:
    assert hitboxes(_framedata("10.0", "--")).select("hitbox", "damage").rows() == [("", 10.0)]
    assert hitboxes(_framedata("2.7 / 3.4", None))["damage"].to_list() == [2.7, 3.4]


def test_non_plain_values_kept_as_null() -> None:
    for raw in ["10.0—27.0", "12.0(9.0)", "--", "Grounded: 28.0%/18.0% | Aerial: 25.0", None]:
        out = hitboxes(_framedata(raw, "--"))
        assert out["damage"].to_list() == [None]
        assert out["raw_damage"].to_list() == [raw]
