# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: offline tests for ds.data.raw.supermajor's page parsing (synthetic Next.js payload).
# Usage: uv run pytest tests/ds/data
# ---------------------------------------------------------------------------
from __future__ import annotations

import json

import pytest
from ds.data.raw.supermajor import (
    ALL_TIME,
    LAST_6_MONTHS,
    PlayerMatch,
    parse_player_usage,
    pick_player,
    resolve_player,
)


def _stage(sid: str, name: str, short: str, played: int, rate: float) -> dict:
    return {"stage_id": sid, "stage_name": name, "short_stage_name": short, "times_played": played, "usage_rate": rate}


def _stage_ctx(*stages: dict, games: int) -> dict:
    return {
        "stages": {s["stage_id"]: s for s in stages},
        "order": [s["stage_id"] for s in stages],
        "metadata": {"num_games_with_stage_data": games},
    }


_PS2 = _stage("A378", "Pokemon Stadium 2", "PS2", 3, 0.75)
_BF = _stage("A311", "Battlefield", "BF", 1, 0.25)

_DATA = {
    "character_info_lookup": {
        "A1297": {"character_id": "A1297", "sport": "ultimate", "name": "Little Mac"},
        "A1299": {"character_id": "A1299", "sport": "ultimate", "name": "Lucas"},
    },
    "characters": {
        "contexts": {
            LAST_6_MONTHS: {
                "characters": {
                    "A1297": {"usage_rate": 0.75, "num_games": 3, "num_wins": 2, "num_losses": 1, "winrate": 2 / 3},
                    "A1299": {"usage_rate": 0.25, "num_games": 1, "num_wins": 0, "num_losses": 1, "winrate": 0.0},
                },
                "order": ["A1297", "A1299"],
            },
            ALL_TIME: {"characters": {}, "order": []},
        }
    },
    "stages": {
        "contexts": {
            "all": _stage_ctx(_PS2, _BF, games=4),
            "starters": _stage_ctx(_PS2, _BF, games=4),
            "counters": _stage_ctx(games=0),
        }
    },
}


def _page(data: dict) -> str:
    """Wrap `data` like Next.js does: a JSON string split across `self.__next_f.push` chunks"""
    text = json.dumps(data)
    half = len(text) // 2
    pushes = "".join(
        f"<script>self.__next_f.push([1,{json.dumps(chunk)}])</script>" for chunk in (text[:half], text[half:])
    )
    return f"<html><body>{pushes}</body></html>"


def test_last_6_months_characters() -> None:
    usage = parse_player_usage(_page(_DATA))
    assert [(c.character, c.usage_pct, c.games) for c in usage.characters] == [
        ("Little Mac", 75.0, 3),
        ("Lucas", 25.0, 1),
    ]


def test_stages() -> None:
    usage = parse_player_usage(_page(_DATA))
    assert usage.starters.games == 4
    assert [(s.short_name, s.usage_pct) for s in usage.starters.stages] == [("PS2", 75.0), ("BF", 25.0)]
    assert usage.counters.stages == []


def test_empty_period() -> None:
    assert parse_player_usage(_page(_DATA), ALL_TIME).characters == []


def test_unknown_period_lists_available() -> None:
    with pytest.raises(ValueError, match="Last 6 Mo"):
        parse_player_usage(_page(_DATA), "Last Year")


def test_resolve_player() -> None:
    by_id = resolve_player("S2884234")
    assert (by_id.match_type, by_id.url.endswith("?id=S2884234")) == ("player_id", True)
    url = "https://www.supermajor.gg/ultimate/player/DeLulu?id=S4734338"
    assert (resolve_player(url).match_type, resolve_player(url).url) == ("url", url)


def test_pick_player_prefers_exact_case_then_most_events() -> None:
    matches = [
        PlayerMatch(player_id="S1", tag="Luke", num_events=167),
        PlayerMatch(player_id="S2", tag="Luke", num_events=75),
        PlayerMatch(player_id="S3", tag="luke", num_events=500),
        PlayerMatch(player_id="S4", tag="Lukedub", num_events=1),
    ]
    exact = pick_player("Luke", matches)
    assert (exact.match_type, exact.player.player_id, exact.tied_matches) == ("tag_exact", "S1", 2)
    any_case = pick_player("LUKE", matches)
    assert (any_case.match_type, any_case.player.player_id, any_case.tied_matches) == ("tag_any_case", "S3", 3)
    assert any_case.search_results == 4
    with pytest.raises(ValueError, match="similar tags"):
        pick_player("Lu", matches)
