#!/usr/bin/env bash
set -euo pipefail

# AUTO-GENERATED by Claude Code
# Purpose: Open Claude Code in the delulu-smash repo, continuing the most recent session there (or starting
#          a fresh one if none exists). Target of an Omarchy keybinding run via `omarchy-launch-or-focus-tui`.
# Usage: claude-delulu.sh [extra claude args]
REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$REPO_DIR"

# Claude stores sessions per project under ~/.claude/projects/<path with / and . replaced by ->.
# `claude --continue` exits with an error when there's nothing to continue, so check first.
SESSION_DIR="$HOME/.claude/projects/$(printf '%s' "$REPO_DIR" | tr '/.' '--')"
if compgen -G "$SESSION_DIR/*.jsonl" >/dev/null; then
  exec claude --continue "$@"
fi
exec claude "$@"
