# AUTO-GENERATED by GitHub Copilot
# Purpose: Typer CLI for toggling Omarchy/Hyprland region recording with clipboard and save modes.
# Usage: called from screenrecord.sh via uv run, or run directly with uv run .os/scripts/keybindings/screenrecord.py.
# Output: records with wf-recorder, converts clipboard clips to GIF when requested, and falls back to saved files if needed.

# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "typer>=0.23.0",
# ]
# ///

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import typer

TMP_DIR = Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp")) / "screenrecord"
SAVE_DIR = Path.home() / "repos" / "delulu-smash" / "local" / "assets" / "snippets"
STATE_DIR = Path(os.environ.get("XDG_STATE_HOME", str(Path.home() / ".local" / "state"))) / "screenrecord"
STATE_FILE = STATE_DIR / "current_recording.txt"
CLEANUP_AFTER_SECONDS = int(os.environ.get("SCREENRECORD_CLIPBOARD_TTL_SECONDS", "180"))
START_DELAY = int(os.environ.get("SCREENRECORD_START_DELAY_SECONDS", "3"))
DEFAULT_CLIPBOARD_FORMAT = os.environ.get("SCREENRECORD_CLIPBOARD_FORMAT", "gif")


def notify(message: str, *, icon: str = "video-x-generic", timeout_ms: int | None = None) -> None:
    if shutil.which("notify-send") is None:
        return

    command = ["notify-send", "Screen Recorder", message, "-i", icon]
    if timeout_ms is not None:
        command.extend(["-t", str(timeout_ms)])
    subprocess.run(command, check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def require_dependencies(commands: tuple[str, ...]) -> None:
    missing = [command for command in commands if shutil.which(command) is None]
    if not missing:
        return

    for command in missing:
        print(f"Missing dependency: {command}", file=sys.stderr)
        notify(f"Missing dependency: {command}", icon="dialog-error")
    raise typer.Exit(1)


def copy_clip_path(file_path: Path) -> bool:
    file_uri = f"file://{file_path}"

    if shutil.which("wl-copy") is not None:
        try:
            subprocess.run(
                ["wl-copy", "--type", "text/uri-list"],
                input=f"{file_uri}\n".encode(),
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    if shutil.which("xclip") is not None:
        try:
            subprocess.run(
                ["xclip", "-selection", "clipboard", "-t", "text/uri-list"],
                input=f"{file_uri}\n".encode(),
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    return False


def copy_clip_bytes(file_path: Path, mime_type: str) -> bool:
    file_bytes = file_path.read_bytes()

    if shutil.which("wl-copy") is not None:
        try:
            subprocess.run(
                ["wl-copy", "--type", mime_type],
                input=file_bytes,
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    if shutil.which("xclip") is not None:
        try:
            subprocess.run(
                ["xclip", "-selection", "clipboard", "-t", mime_type],
                input=file_bytes,
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    return False


def convert_mp4_to_gif(input_file: Path, output_file: Path) -> bool:
    if shutil.which("ffmpeg") is None:
        return False

    fps = os.environ.get("SCREENRECORD_GIF_FPS", "12")
    width = os.environ.get("SCREENRECORD_GIF_WIDTH", "960")

    palette_fd, palette_name = tempfile.mkstemp(suffix=".png")
    os.close(palette_fd)
    palette_file = Path(palette_name)

    try:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-loglevel",
                "error",
                "-i",
                str(input_file),
                "-vf",
                f"fps={fps},scale={width}:-1:flags=lanczos,palettegen=stats_mode=diff",
                str(palette_file),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-loglevel",
                "error",
                "-i",
                str(input_file),
                "-i",
                str(palette_file),
                "-lavfi",
                f"fps={fps},scale={width}:-1:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle",
                str(output_file),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return False
    finally:
        palette_file.unlink(missing_ok=True)

    return True


def schedule_cleanup(file_path: Path, ttl_seconds: int) -> None:
    subprocess.Popen(
        ["bash", "-c", 'sleep "$1"; rm -f -- "$2"', "_", str(ttl_seconds), str(file_path)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


def parse_state(state_content: str) -> tuple[str, str, str]:
    if state_content.count("\t") >= 2:
        record_mode, record_format, last_file = state_content.split("\t", 2)
        return record_mode, record_format, last_file

    if "\t" in state_content:
        record_mode, last_file = state_content.split("\t", 1)
        return record_mode, "gif", last_file

    return "clipboard", "gif", state_content


def stop_recording() -> None:
    subprocess.run(
        ["pkill", "-INT", "-x", "wf-recorder"], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )

    if not STATE_FILE.exists():
        notify("Recording stopped")
        return

    state_content = STATE_FILE.read_text(encoding="utf-8").strip()
    record_mode, record_format, last_file = parse_state(state_content)
    last_path = Path(last_file)

    try:
        if record_mode == "save":
            if copy_clip_path(last_path):
                notify(f"Saved clip and copied file reference: {last_path.name}")
            else:
                notify(f"Saved clip: {last_path.name}")
            return

        if record_format == "gif":
            gif_path = last_path.with_suffix(".gif")

            if convert_mp4_to_gif(last_path, gif_path):
                last_path.unlink(missing_ok=True)

                if copy_clip_path(gif_path):
                    schedule_cleanup(gif_path, CLEANUP_AFTER_SECONDS)
                    notify(f"Copied GIF reference to clipboard (temp auto-delete in {CLEANUP_AFTER_SECONDS}s)")
                elif copy_clip_bytes(gif_path, "image/gif"):
                    gif_path.unlink(missing_ok=True)
                    notify("Copied GIF bytes to clipboard (temporary file removed)")
                else:
                    fallback_path = SAVE_DIR / gif_path.name
                    fallback_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(gif_path), str(fallback_path))
                    notify(f"Clipboard copy failed; GIF kept at {fallback_path.name}")
                return

            if copy_clip_path(last_path):
                schedule_cleanup(last_path, CLEANUP_AFTER_SECONDS)
                notify(f"GIF conversion failed, copied MP4 reference (temp auto-delete in {CLEANUP_AFTER_SECONDS}s)")
            elif copy_clip_bytes(last_path, "video/mp4"):
                last_path.unlink(missing_ok=True)
                notify("GIF conversion failed, copied MP4 bytes (temporary file removed)")
            else:
                fallback_path = SAVE_DIR / last_path.name
                fallback_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(last_path), str(fallback_path))
                notify(f"Clipboard copy failed; MP4 kept at {fallback_path.name}")
            return

        if copy_clip_path(last_path):
            schedule_cleanup(last_path, CLEANUP_AFTER_SECONDS)
            notify(f"Copied MP4 reference to clipboard (temp auto-delete in {CLEANUP_AFTER_SECONDS}s)")
        elif copy_clip_bytes(last_path, "video/mp4"):
            last_path.unlink(missing_ok=True)
            notify("Copied MP4 bytes to clipboard (temporary file removed)")
        else:
            fallback_path = SAVE_DIR / last_path.name
            fallback_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(last_path), str(fallback_path))
            notify(f"Clipboard copy failed; MP4 kept at {fallback_path.name}")
    finally:
        STATE_FILE.unlink(missing_ok=True)


def start_recording(*, save_mode: bool, clipboard_format: str) -> None:
    try:
        geometry = subprocess.run(
            ["slurp", "-b", "000000a0", "-c", "00aaffff", "-w", "2"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError:
        return

    if not geometry:
        return

    if START_DELAY > 0:
        for remaining in range(START_DELAY, 0, -1):
            notify(f"Starting in {remaining}...", timeout_ms=900)
            time.sleep(1)

    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
    output_file = SAVE_DIR / f"snippet_{timestamp}.mp4" if save_mode else TMP_DIR / f"snippet_{timestamp}.mp4"

    TMP_DIR.mkdir(parents=True, exist_ok=True)
    SAVE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_DIR.mkdir(parents=True, exist_ok=True)

    STATE_FILE.write_text(
        f"{'save' if save_mode else 'clipboard'}\t{clipboard_format}\t{output_file}\n", encoding="utf-8"
    )
    notify("Recording started")

    subprocess.Popen(
        ["wf-recorder", "-g", geometry, "-f", str(output_file)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


def main(
    save_mode: bool = typer.Option(False, "--save", help="Keep recordings in local/assets/snippets."),
    gif_mode: bool = typer.Option(False, "--gif", help="Convert clipboard recordings to GIF on stop."),
    mp4_mode: bool = typer.Option(False, "--mp4", help="Keep clipboard recordings as MP4 on stop."),
    clipboard_format: str = typer.Option(
        DEFAULT_CLIPBOARD_FORMAT,
        "--format",
        help="Clipboard format to use when no explicit format flag is set.",
    ),
) -> None:
    require_dependencies(("wf-recorder", "slurp", "notify-send"))

    resolved_format = clipboard_format.lower()
    if mp4_mode:
        resolved_format = "mp4"
    elif gif_mode:
        resolved_format = "gif"

    if resolved_format not in {"gif", "mp4"}:
        notify(f"Invalid format: {resolved_format} (use gif or mp4)", icon="dialog-error")
        raise typer.Exit(1)

    if (
        subprocess.run(
            ["pgrep", "-x", "wf-recorder"], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        ).returncode
        == 0
    ):
        stop_recording()
        return

    start_recording(save_mode=save_mode, clipboard_format=resolved_format)


if __name__ == "__main__":
    typer.run(main)
