#!/usr/bin/env bash
set -euo pipefail

# AUTO-GENERATED by GitHub Copilot
# Purpose: Thin launcher for the screenrecord Typer CLI used by Omarchy keybindings.
# Usage: screenrecord.sh [--gif|--mp4|--save]
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

exec uv run "$SCRIPT_DIR/screenrecord.py" "$@"