#!/usr/bin/env bash
set -euo pipefail

# AUTO-GENERATED by Claude Code
# Purpose: Launch the experimental/textual-kernel TUI; target of an Omarchy keybinding, which runs it
#          inside the default terminal via `omarchy-launch-or-focus-tui`.
# Usage: textual-kernel.sh [args passed to textual-kernel]
REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd)"

cd "$REPO_DIR/experimental/textual-kernel"
exec uv run textual-kernel "$@"
