#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: AI post-edit hook -- report-only lint (`ds lint file`) of a just-edited .py file.
# Input: hook JSON on stdin (reads .tool_input.file_path); non-.py files are skipped.
# Output: exit 0 when clean; lint errors on stderr + exit 2 (Claude Code feeds that back to
#         the model) otherwise. Wired up in .claude/settings.json (PostToolUse, Edit|Write).
#
# Example CLI Commands:
#   1. Manual test: echo '{"tool_input":{"file_path":"pkgs/ds/cli/lint.py"}}' | .agents/hooks/post_edit_lint.sh
# ---------------------------------------------------------------------------

file=$(jq -r '.tool_input.file_path // empty')
case "$file" in
    *.py) ;;
    *) exit 0 ;;
esac

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
if ! output=$(uv run --project "$repo_dir" ds lint file "$file" 2>&1); then
    {
        echo "Lint errors in $file (ruff, report-only). Fix those in code you touched; if a rule"
        # TODO: see if want this to be instead not silently fail lint errors and ask for human intervention
        echo "genuinely doesn't fit, add a targeted '# noqa: CODE  # reason' instead of looping:"
        echo "$output"
    } >&2
    exit 2
fi
