# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: `ds lint` subcommands -- run the repo's pre-commit hooks (ruff lint/format, etc from
#          .pre-commit-config.yaml) on demand, without needing a commit.
#
# Example CLI Commands:
#   1. Same as a git commit (staged): ds lint run
#   2. Every file in the repo:        ds lint run --all-files
#   3. A single hook:                 ds lint run ruff
#   4. Report-only check of a file:   ds lint file pkgs/ds/cli/lint.py
#      (used by the Claude Code post-edit hook, see .agents/hooks/post_edit_lint.sh)
# ---------------------------------------------------------------------------
from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Annotated

import typer
import yaml
from ds.cli.util import run_cmd
from ds.util.const import REPO_DIR

__all__ = ["lint_app"]

lint_app = typer.Typer(help="SubCommands for linting")

PRE_COMMIT_CONFIG = REPO_DIR / ".pre-commit-config.yaml"


@lint_app.command("run")
def run(
    hook: Annotated[
        str | None, typer.Argument(help="Only run this hook id (eg ruff, ruff-format); default all hooks")
    ] = None,
    all_files: Annotated[
        bool,
        typer.Option("--all-files/--staged", help="Check every file, or only staged ones (what git commit runs)"),
    ] = False,
) -> None:
    """Run pre-commit hooks -- by default exactly what `git commit` runs (staged files only)"""
    # via this interpreter's own pre-commit (a project dependency): no .venv/bin on PATH needed
    cmds = [sys.executable, "-m", "pre_commit", "run"]
    if hook:
        cmds.append(hook)
    if all_files:
        cmds.append("--all-files")
    try:
        run_cmd(cmds, cwd=REPO_DIR)
    except subprocess.CalledProcessError as exc:
        # hooks failing (or auto-fixing files) is normal, not a crash -- pass the exit code on
        raise typer.Exit(exc.returncode) from None


@lint_app.command("file")
def file(
    paths: Annotated[list[Path], typer.Argument(help="Python files to check")],
) -> None:
    """Report-only ruff check (no auto-fix): safe between edits, eg in AI post-edit hooks"""
    cmds = [
        "uvx",
        f"ruff@{_ruff_version()}",
        "check",
        "--no-fix",
        # unused imports are usually mid-edit (added before the code using them);
        # `ds lint run` still catches real ones
        "--extend-ignore=F401",
        "--output-format=concise",
        # still honor pyproject excludes (eg experimental/) when given explicit paths
        "--force-exclude",
        # resolved here since ruff runs from the repo root, not the caller's directory
        *[str(p.resolve()) for p in paths],
    ]
    result = subprocess.run(cmds, cwd=REPO_DIR, check=False)
    if result.returncode:
        raise typer.Exit(result.returncode)


def _ruff_version() -> str:
    """Ruff version pinned for the pre-commit hook, so this never drifts from `ds lint run`"""
    config = yaml.safe_load(PRE_COMMIT_CONFIG.read_text())
    for repo in config["repos"]:
        if repo["repo"].rstrip("/").removesuffix(".git").endswith("astral-sh/ruff-pre-commit"):
            return repo["rev"].removeprefix("v")
    msg = f"no ruff-pre-commit repo found in {PRE_COMMIT_CONFIG}"
    raise RuntimeError(msg)
