# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: tests for ds.calc.little_mac (Straight Lunge armor), cross-checked against the
#          community "SL Armour Broken" sheet (DK tab), including its known differences.
# Usage: uv run pytest tests/ds/calc
# ---------------------------------------------------------------------------
from __future__ import annotations

import polars as pl
import pytest
from ds.calc.little_mac import SL_ARMOR_UNCHARGED, armor_result, straight_lunge_armor
from ds.calc.stale import REDUCTORS, min_stales

# DK tab of the SL Armour sheet, pulled 2026-09-30:
# https://docs.google.com/spreadsheets/d/1kpnXzwdspS1kR-rQWFm0l2GejtRfR_tmc-U6IA8JwRU/edit?gid=909113482  # noqa: E501, W505  # URL
# Rows: (base damage, sheet "1v1 w/ Freshness" damage, sheet stales to armor), one per
# distinct base damage; stales 0 = "Always", None = "Unarmorable"
SHEET_ROWS = [
    (0.6, 0.75, 0), (1.4, 1.75, 0), (1.6, 2.0, 0), (4, 5, 0), (5, 6.25, 0), (6, 7.5, 0), (6.8, 8.5, 0),
    (7, 8.75, 0), (8, 10, 1), (9, 11.25, 2), (9.35, 11.6875, 3), (10, 12.5, 3), (11, 13.75, 4),
    (11.05, 13.8125, 4), (12, 15, 5), (12.75, 15.9375, 6), (13, 16.25, 6), (13.6, 17, 7), (14, 17.5, 7),
    (15, 18.75, 8), (16, 20, 9), (17, 21.25, None), (18, 22.5, None), (19, 23.75, None), (21, 26.25, None),
    (22, 27.5, None),
]  # fmt: skip
# rows where the stale rules (freshness only while fresh) need fewer stales than the sheet
SHEET_DIFFERENCES = {9.35: 2, 12.75: 5, 13.6: 6, 14: 6, 15: 7, 16: 8, 17: 9}


def _sheet_formula(sheet_1v1_damage: float) -> int | None:
    """The sheet's apparent rule: 1v1+freshness damage x (1 - reductors) <= 9.6 (8 x 1.2)."""
    for k in range(len(REDUCTORS) + 1):
        if sheet_1v1_damage * (1 - sum(REDUCTORS[:k])) <= SL_ARMOR_UNCHARGED * 1.2:
            return k
    return None


@pytest.mark.parametrize("row", SHEET_ROWS)
def test_sheet_formula_explains_every_row(row: tuple[float, float, int | None]) -> None:
    # confirms how the sheet was computed (freshness kept after staling)
    _, sheet_1v1, sheet_stales = row
    assert _sheet_formula(sheet_1v1) == sheet_stales


@pytest.mark.parametrize("row", SHEET_ROWS)
def test_ours_matches_sheet_except_d004(row: tuple[float, float, int | None]) -> None:
    base, _, sheet_stales = row
    expected = SHEET_DIFFERENCES.get(base, sheet_stales)
    assert min_stales(base, SL_ARMOR_UNCHARGED) == expected


@pytest.mark.parametrize(
    ("damage", "expected"),
    [(None, "not computed"), (6.0, "fresh"), (8.0, "after 1 stale"), (12.0, "after 5 stales"), (22.0, "never")],
)
def test_armor_result_labels(damage: float | None, expected: str) -> None:
    assert armor_result(damage, SL_ARMOR_UNCHARGED) == expected


def test_straight_lunge_armor_variants_and_skips() -> None:
    hitboxes = pl.DataFrame(
        {
            "char_id": ["donkey_kong"] * 4,
            "category": ["Aerial Attacks", "Ground Attacks", "Grabs / Throws", "Special Attacks"],
            "move": ["Neutral Air", "Forward Smash", "Pummel", "Neutral B (Giant Punch)"],
            "hitbox": ["Early", "Far", "", ""],
            "damage": [12.0, 22.0, 1.6, None],
            "raw_damage": ["12.0/9.0", "22.0/21.0", "1.6", "10.0—27.0"],
        }
    )
    out = straight_lunge_armor(hitboxes)
    assert "Pummel" not in out["move"].to_list()
    nair_sh = out.filter((pl.col("move") == "Neutral Air") & (pl.col("variant") == "short hop attack"))
    assert nair_sh["damage"].item() == pytest.approx(10.2)
    fsmash_charged = out.filter((pl.col("move") == "Forward Smash") & (pl.col("variant") == "full charge"))
    assert fsmash_charged["damage"].item() == pytest.approx(30.8)
    giant_punch = out.filter(pl.col("move") == "Neutral B (Giant Punch)")
    assert giant_punch["uncharged"].item() == "not computed"
