# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: tests for ds.calc.stale (docs sync checks live in test_docs_sync.py).
# Usage: uv run pytest tests/ds/calc
# ---------------------------------------------------------------------------
from __future__ import annotations

import pytest
from ds.calc.stale import FRESHNESS_BONUS, REDUCTORS, SHIELD_REDUCTOR_FACTOR, min_stales, stale_factor


def test_fresh_and_full_stale() -> None:
    assert stale_factor() == FRESHNESS_BONUS
    assert stale_factor(times_used=9) == pytest.approx(0.4695)


def test_positions_worked_example_from_docs() -> None:
    # docs: positions 1, 2 and 6 -> 77.42% of base damage
    assert stale_factor(positions=[1, 2, 6]) == pytest.approx(0.7742)


def test_shield_positions_use_reduced_reductor() -> None:
    assert stale_factor(shield_positions=[1]) == pytest.approx(1 - REDUCTORS[0] * SHIELD_REDUCTOR_FACTOR)


@pytest.mark.parametrize(
    ("kwargs", "match"),
    [
        ({"times_used": 10}, "times_used"),
        ({"positions": [0]}, "positions"),
        ({"positions": [1], "shield_positions": [1]}, "both hit and shield"),
    ],
)
def test_invalid_positions(kwargs: dict, match: str) -> None:
    with pytest.raises(ValueError, match=match):
        stale_factor(**kwargs)


@pytest.mark.parametrize(
    ("damage", "expected"),
    [
        (7.0, 0),  # 7 * 1.05 = 7.35 <= 8, tanked fresh
        (8.0, 1),  # 8 * 1.05 = 8.4 > 8, but 8 * 0.91 = 7.28
        (12.0, 5),
        (17.0, 9),  # 17 * 0.4695 = 7.98, only fully stale
        (18.0, None),  # 18 * 0.4695 = 8.45, never
    ],
)
def test_min_stales(damage: float, expected: int | None) -> None:
    assert min_stales(damage, threshold=8.0) == expected
