# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: sync tests between docs/ tables and the ds.calc constants built from them. If a
#          docs number changes, the failing test names the constant to update.
# Usage: uv run pytest tests/ds/calc/test_docs_sync.py
# ---------------------------------------------------------------------------
from __future__ import annotations

import re

import polars as pl
import pytest
from ds.calc import modifiers
from ds.calc.little_mac import SL_ARMOR_FULL_CHARGE, SL_ARMOR_UNCHARGED
from ds.calc.modifiers import (
    ONE_V_ONE_MULTIPLIER,
    SHORT_HOP_ATTACK_MULTIPLIER,
    SMASH_ATTACKS,
    SMASH_FULL_CHARGE_MULTIPLIER,
    smash_full_charge_multiplier,
)
from ds.calc.stale import FRESHNESS_BONUS, REDUCTORS, SHIELD_REDUCTOR_FACTOR
from ds.util.docs import docs_table


def _number(text: str) -> float:
    """First number in a cell, eg "That slot's reductor x 0.85" -> 0.85."""
    match = re.search(r"\d+(?:\.\d+)?", text)
    assert match, f"no number in {text!r}"
    return float(match.group())


def _row(table: pl.DataFrame, starts_with: str) -> dict:
    """The row whose first column starts with `starts_with`."""
    first = table.columns[0]
    rows = table.filter(pl.col(first).str.starts_with(starts_with)).to_dicts()
    assert len(rows) == 1, f"expected one {starts_with!r} row in {first!r}, got {len(rows)}"
    return rows[0]


# docs/mechanics/stale_moves.md


def test_stale_reductors() -> None:
    table = docs_table("stale-reductors").filter(pl.col("Queue position").str.contains(r"^\d$"))
    assert [float(v) for v in table["Reductor"]] == list(REDUCTORS)


def test_stale_multipliers() -> None:
    table = docs_table("stale-multipliers")
    assert _number(_row(table, "Fresh (")["Damage multiplier"]) == FRESHNESS_BONUS
    assert _number(_row(table, "Slot filled by a shield hit")["Damage multiplier"]) == SHIELD_REDUCTOR_FACTOR


# docs/moveset.md (Straight Lunge armor)


def test_sl_armor_thresholds() -> None:
    table = docs_table("sl-armor-thresholds")
    for charge, threshold in [("Uncharged", SL_ARMOR_UNCHARGED), ("Full charge", SL_ARMOR_FULL_CHARGE)]:
        row = _row(table, charge)
        assert _number(row["Tanks hits up to (base damage)"]) == threshold
        assert _number(row["Same threshold as shown in 1v1"]) == pytest.approx(threshold * ONE_V_ONE_MULTIPLIER)


def test_sl_armor_modifiers() -> None:
    table = docs_table("sl-armor-modifiers")
    assert _number(_row(table, "Freshness")["Multiplier"]) == FRESHNESS_BONUS
    assert _number(_row(table, "Short hop attack")["Multiplier"]) == SHORT_HOP_ATTACK_MULTIPLIER
    assert _number(_row(table, "Fully charged smash attack")["Multiplier"]) == SMASH_FULL_CHARGE_MULTIPLIER


def test_smash_charge_exceptions() -> None:
    table = docs_table("smash-charge-exceptions")
    documented = {}
    for row in table.iter_rows(named=True):
        char_id = row["Character"].lower().replace(" ", "_")
        smashes = SMASH_ATTACKS if row["Smash attacks"] == "all" else tuple(row["Smash attacks"].split(", "))
        documented[char_id] = smashes
        for move in smashes:
            assert smash_full_charge_multiplier(char_id, move) == _number(row["Full-charge multiplier"])
    # and nothing in code that the docs don't list
    code = {c: m or SMASH_ATTACKS for c, m in modifiers._SMASH_1_2X.items()}
    assert code == documented
