# ---------------------------------------------------------------------------
# AUTO-GENERATED by GitHub Copilot
# Purpose: Scrape per-character move frame data from ultimateframedata.com into a polars DataFrame.
# Usage: `scrape_framedata("little_mac")` returns one row per move (ground/aerial/special/grab/dodge).
# ---------------------------------------------------------------------------
from __future__ import annotations

import httpx2
import polars as pl
from bs4 import BeautifulSoup, Tag

BASE_URL = "https://ultimateframedata.com/{character}"
USER_AGENT = "Mozilla/5.0 (compatible; delulu-smash-framedata-scraper)"

# these categories hold structured per-move frame data (misc/stats section is unstructured prose)
MOVE_CATEGORY_IDS = ["groundattacks", "aerialattacks", "specialattacks", "grabs", "dodges"]


def _parse_move(container: Tag, category: str) -> dict[str, str]:
    row: dict[str, str] = {"category": category}
    for div in container.find_all("div", recursive=False):
        classes = div.get("class") or []
        if "hitbox" in classes:
            continue
        key = "move" if "movename" in classes else (classes[0] if classes else "value")
        row[key] = " ".join(div.get_text(strip=True, separator=" ").split())
    return row


def scrape_framedata(character: str) -> pl.DataFrame:
    """Scrape ultimateframedata.com for a character (eg "little_mac") into a polars DataFrame."""
    url = BASE_URL.format(character=character)
    resp = httpx2.get(url, headers={"User-Agent": USER_AGENT}, timeout=30, follow_redirects=True)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    rows: list[dict[str, str]] = []
    for category_id in MOVE_CATEGORY_IDS:
        heading = soup.find("h2", id=category_id)
        if heading is None:
            continue
        moves_div = heading.find_next_sibling("div", class_="moves")
        if moves_div is None:
            continue
        for container in moves_div.find_all("div", class_="movecontainer", recursive=False):
            rows.append(_parse_move(container, heading.get_text(strip=True)))

    return pl.DataFrame(rows)
