# ---------------------------------------------------------------------------
# AUTO-GENERATED by GitHub Copilot
# Purpose: Scrape per-character move frame data from ultimateframedata.com into a polars DataFrame.
# Usage: `scrape_framedata("little_mac")` returns one row per move (ground/aerial/special/grab/dodge).
#
# Site is plain static/server-rendered HTML (verified via raw httpx2 GET, no JS execution needed).
# Each move is a `.movecontainer` div whose direct child divs are keyed by CSS class (eg `.startup`,
# `.basedamage`) -- so parsing is just "class name -> column name", no fixed schema per move type.
# Different move types have different fields (eg aerials add `hopsautocancel`/`hopsactionable`,
# some characters have oddball fields like `pikminbox`), so columns are NOT fixed across characters --
# always union/concat with `how="diagonal_relaxed"` when combining multiple characters' scrapes.
# ---------------------------------------------------------------------------
from __future__ import annotations

# TOOD: need to get datatypes of parquet files (all str, and some are like 4/6/2)
# may want to think if want pydantic classes that return from it/establish what should scrape?
# TODO: have temp/ folder that stores parquet and SmashRawDb so can query easily
import httpx2
import polars as pl
from bs4 import BeautifulSoup, Tag

BASE_URL = "https://ultimateframedata.com/{character}"
USER_AGENT = "Mozilla/5.0 (compatible; delulu-smash-framedata-scraper)"

# these categories hold structured per-move frame data (misc/stats section is unstructured prose)
# ids come from each section's <h2 id="..."> heading; each heading is followed by a sibling <div class="moves">
MOVE_CATEGORY_IDS = ["groundattacks", "aerialattacks", "specialattacks", "grabs", "dodges"]


def _parse_move(container: Tag, category: str, character: str) -> dict[str, str]:
    row: dict[str, str] = {"char_id": character, "category": category}
    for div in container.find_all("div", recursive=False):
        classes = div.get("class") or []
        if "hitbox" in classes:
            continue  # this is just the hitbox gif thumbnail/link, not a frame-data field
        key = "move" if "movename" in classes else (classes[0] if classes else "value")
        row[key] = " ".join(div.get_text(strip=True, separator=" ").split())
    return row


def scrape_framedata(character: str) -> pl.DataFrame:
    """Scrape ultimateframedata.com for a character (eg "little_mac") into a polars DataFrame."""
    # character must be the exact URL slug (see char.parquet id / roster.py), not the display name --
    # slugs sometimes differ from what you'd guess (eg donkey_kong not dk, king_dedede not king_ddd)
    url = BASE_URL.format(character=character)
    resp = httpx2.get(url, headers={"User-Agent": USER_AGENT}, timeout=30, follow_redirects=True)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    rows: list[dict[str, str]] = []
    for category_id in MOVE_CATEGORY_IDS:
        heading = soup.find("h2", id=category_id)
        if heading is None:
            continue
        moves_div = heading.find_next_sibling("div", class_="moves")
        if moves_div is None:
            continue
        for container in moves_div.find_all("div", class_="movecontainer", recursive=False):
            rows.append(_parse_move(container, heading.get_text(strip=True), character))

    return pl.DataFrame(rows)
