# ---------------------------------------------------------------------------
# AUTO-GENERATED by GitHub Copilot
# Purpose: Scrape the full character roster from ultimateframedata.com/smash into a polars DataFrame.
# Usage: `scrape_character_roster()` returns one row per character (id = URL slug, name = display name).
# ---------------------------------------------------------------------------
from __future__ import annotations

import httpx2
import polars as pl
from bs4 import BeautifulSoup

from ds.data.raw.framedata import BASE_URL

ROSTER_URL = "https://ultimateframedata.com/smash"
USER_AGENT = "Mozilla/5.0 (compatible; delulu-smash-framedata-scraper)"


def scrape_character_roster() -> pl.DataFrame:
    """Scrape ultimateframedata.com/smash for every character's URL slug (id) and display name"""
    resp = httpx2.get(ROSTER_URL, headers={"User-Agent": USER_AGENT}, timeout=30, follow_redirects=True)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    rows: list[dict[str, str]] = []
    for icon in soup.find_all("div", class_="charactericon"):
        link = icon.find("a")
        if link is None:
            continue
        href = link.get("href", "")
        slug = href.lstrip("/")
        if slug == "stats":
            continue  # not a character, just a link to the site's stats page
        # TODO: see if framedata_url should store given its just derived by id
        rows.append({"id": slug, "name": link.get("title", ""), "framedata_url": BASE_URL.format(character=slug)})

    return pl.DataFrame(rows)
