# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: Scrape a player's character usage (eg "Last 6 Months") and starter/counterpick
# stage usage from a supermajor.gg player page. The page is server-rendered Next.js: the
# stats live in its embedded RSC payload (`self.__next_f.push`), so plain httpx2 works.
# Usage: `player_usage(url)` with a player page url (see `scripts/supermajor_usage.py`).
# ---------------------------------------------------------------------------
from __future__ import annotations

import json
import re

import httpx2
from pydantic import BaseModel, Field

# A regular desktop Chrome UA, so requests look like a normal browser visit
USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
LAST_6_MONTHS = "Last 6 Mo"  # the page's own key; the UI shows it as "Last 6 Months"
ALL_TIME = "All Time"

_PUSH_RE = re.compile(r"self\.__next_f\.push\(\[1,(\"(?:[^\"\\]|\\.)*\")\]\)")


class CharacterUsage(BaseModel):
    """One character's share of a player's games in a period"""

    character_id: str = Field(description="supermajor.gg character id, eg 'A1297'")
    character: str = Field(description="Display name, eg 'Little Mac'")
    usage_pct: float = Field(description="0-100, share of the period's games that have character data")
    games: int
    wins: int
    losses: int
    winrate: float = Field(description="0-1, game winrate on this character")


class StageUsage(BaseModel):
    """One stage's share of a player's games in a stage category"""

    stage_id: str = Field(description="supermajor.gg stage id, eg 'A378'")
    stage: str = Field(description="Display name, eg 'Pokemon Stadium 2'")
    short_name: str = Field(description="Abbreviation, eg 'PS2'")
    usage_pct: float = Field(description="0-100, share of the category's games with stage data")
    games: int


class StageStats(BaseModel):
    """Stage usage for one category (starters, counters or all), most-played first"""

    games: int = Field(description="Games in this category that have stage data")
    stages: list[StageUsage]


class PlayerUsage(BaseModel):
    """A supermajor.gg player's character and stage usage"""

    period: str = Field(description="Period the `characters` list covers, eg 'Last 6 Mo'")
    characters: list[CharacterUsage] = Field(description="Most-played first")
    starters: StageStats = Field(description="Game 1 (starter) stages; not split by period on the page")
    counters: StageStats = Field(description="Counterpick stages; not split by period on the page")
    all_stages: StageStats = Field(description="Every game with stage data, any category")


def fetch_player_page(url: str) -> str:
    """Download a supermajor.gg player page's HTML"""
    resp = httpx2.get(url, headers={"User-Agent": USER_AGENT}, timeout=30, follow_redirects=True)
    resp.raise_for_status()
    return resp.text


def _flight_payload(html: str) -> str:
    """Concatenate the page's Next.js RSC chunks into one decoded string"""
    return "".join(json.loads(chunk) for chunk in _PUSH_RE.findall(html))


def _json_after(text: str, pattern: str) -> dict:
    """Decode the JSON object right after the first match of regex `pattern` (ending in `:`)"""
    match = re.search(pattern + r"\s*", text)
    if match is None:
        raise ValueError(f"{pattern!r} not found in page data (did the supermajor.gg page format change?)")
    obj, _ = json.JSONDecoder().raw_decode(text, match.end())
    return obj


def _contexts(payload: str, key: str) -> dict:
    """The `contexts` dict of a `"<key>": {"contexts": ...}` section, eg `characters`"""
    return _json_after(payload, rf'"{key}":(?=\s*\{{\s*"contexts")')["contexts"]


def _stage_stats(ctx: dict) -> StageStats:
    stages = [
        StageUsage(
            stage_id=sid,
            stage=ctx["stages"][sid]["stage_name"],
            short_name=ctx["stages"][sid]["short_stage_name"],
            usage_pct=ctx["stages"][sid]["usage_rate"] * 100,
            games=ctx["stages"][sid]["times_played"],
        )
        for sid in ctx["order"]
    ]
    return StageStats(games=ctx["metadata"]["num_games_with_stage_data"], stages=stages)


def parse_player_usage(html: str, period: str = LAST_6_MONTHS) -> PlayerUsage:
    """Parse character usage for `period` plus stage usage out of a player page's HTML

    Args:
        html: the player page HTML, eg from `fetch_player_page`.
        period: the page's character period key, `LAST_6_MONTHS` ("Last 6 Mo") or `ALL_TIME`.
    """
    payload = _flight_payload(html)
    char_contexts = _contexts(payload, "characters")
    if period not in char_contexts:
        raise ValueError(f"unknown period {period!r}; available: {list(char_contexts)}")
    names = {cid: info["name"] for cid, info in _json_after(payload, '"character_info_lookup":').items()}
    ctx = char_contexts[period]
    characters = [
        CharacterUsage(
            character_id=cid,
            character=names.get(cid, cid),
            usage_pct=ctx["characters"][cid]["usage_rate"] * 100,
            games=ctx["characters"][cid]["num_games"],
            wins=ctx["characters"][cid]["num_wins"],
            losses=ctx["characters"][cid]["num_losses"],
            winrate=ctx["characters"][cid]["winrate"],
        )
        for cid in ctx["order"]
    ]
    stage_contexts = _contexts(payload, "stages")
    return PlayerUsage(
        period=period,
        characters=characters,
        starters=_stage_stats(stage_contexts["starters"]),
        counters=_stage_stats(stage_contexts["counters"]),
        all_stages=_stage_stats(stage_contexts["all"]),
    )


def player_usage(url: str, period: str = LAST_6_MONTHS) -> PlayerUsage:
    """Fetch a supermajor.gg player page: character usage for `period`, plus stage usage"""
    return parse_player_usage(fetch_player_page(url), period)
