# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: render one AI-cell run's pydantic-ai messages as a readable trace -- model requests,
#          capability loads, tool calls (args) and returns (results), retries, thinking.
# Used by Cell to build the collapsible debug section under an AI reply (toggle: Ctrl+G).
# ---------------------------------------------------------------------------
from __future__ import annotations

import json
from typing import Any

from pydantic_ai.messages import (
    LoadCapabilityCallPart,
    LoadCapabilityReturnPart,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    RetryPromptPart,
    TextPart,
    ThinkingPart,
    ToolCallPart,
    ToolReturnPart,
    UserPromptPart,
)
from rich.console import Group
from rich.text import Text

# Per-value cap: a tool can return hundreds of rows, which would bury the
# rest of the trace. The full value is still in Kernel.ai_history.
MAX_VALUE_CHARS = 1500


def _clip(value: str, limit: int = MAX_VALUE_CHARS) -> str:
    if len(value) <= limit:
        return value
    return f"{value[:limit]}… ({len(value) - limit} more chars)"


def _pretty(value: Any) -> str:
    try:
        return json.dumps(value, indent=2, ensure_ascii=False, default=str)
    except (TypeError, ValueError):
        return str(value)


def summary(messages: list[ModelMessage]) -> str:
    """Collapsible title, eg 'debug · 2 requests · 1 capability · 1 tool call'."""
    requests = capabilities = tools = 0
    for message in messages:
        if isinstance(message, ModelResponse):
            requests += 1
            for part in message.parts:
                if isinstance(part, LoadCapabilityCallPart):
                    capabilities += 1
                elif isinstance(part, ToolCallPart):
                    tools += 1
    bits = [f"{requests} request{'s' * (requests != 1)}"]
    if capabilities:
        bits.append(f"{capabilities} capability load{'s' * (capabilities != 1)}")
    bits.append(f"{tools} tool call{'s' * (tools != 1)}")
    return "debug · " + " · ".join(bits)


def render(messages: list[ModelMessage]) -> Group:
    """One line (plus an indented body where useful) per interesting part, in run order."""
    lines: list[Text] = []
    request_number = 0

    def body(value: str, style: str = "") -> None:
        lines.append(Text("    " + _clip(value).replace("\n", "\n    "), style=style or "dim"))

    for message in messages:
        if isinstance(message, ModelResponse):
            request_number += 1
            usage = message.usage
            lines.append(
                Text.assemble(
                    (f"● model request {request_number}", "bold"),
                    (f" · {message.model_name or '?'} · {usage.input_tokens} in / {usage.output_tokens} out", "dim"),
                )
            )
            for part in message.parts:
                if isinstance(part, LoadCapabilityCallPart):
                    lines.append(Text(f"  ⚡ load capability {part.args_as_dict().get('id', '?')!r}", style="magenta"))
                elif isinstance(part, ToolCallPart):
                    lines.append(Text(f"  → {part.tool_name}", style="cyan bold"))
                    body(_pretty(part.args_as_dict()))
                elif isinstance(part, ThinkingPart) and part.content:
                    lines.append(Text("  … thinking", style="italic"))
                    body(part.content)
                elif isinstance(part, TextPart) and part.content:
                    lines.append(Text(f"  ✎ text ({len(part.content)} chars)", style="dim"))
        elif isinstance(message, ModelRequest):
            for part in message.parts:
                if isinstance(part, UserPromptPart):
                    lines.append(Text(f"▸ prompt: {_clip(str(part.content), 200)}", style="dim"))
                elif isinstance(part, LoadCapabilityReturnPart):
                    lines.append(Text(f"  ← capability loaded ({part.tool_name})", style="magenta"))
                elif isinstance(part, ToolReturnPart):
                    lines.append(Text(f"  ← {part.tool_name}", style="green bold"))
                    body(_pretty(part.content))
                elif isinstance(part, RetryPromptPart):
                    lines.append(Text(f"  ↻ retry {part.tool_name or ''}".rstrip(), style="yellow bold"))
                    body(part.content if isinstance(part.content, str) else _pretty(part.content), style="yellow")
    return Group(*lines)
