# AUTO-GENERATED by Claude Code
from __future__ import annotations

from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.containers import VerticalScroll
from textual.widgets import Footer, Header

from .cell import Cell
from .editor import CodeEditor
from .kernel import Kernel
from .theme import EVERFOREST_DARK


class NotebookApp(App):
    """A tiny Jupyter-like notebook: cells share one persistent kernel."""

    TITLE = "textual-kernel"
    CSS = """
    #cells {
        padding: 1 2;
        scrollbar-size-vertical: 1;
    }
    /* Here, not in Cell.DEFAULT_CSS: a widget's default CSS is scoped to
       that widget, so an ancestor selector like #cells never matches there.
       CSS-driven so toggling also reveals traces of replies already run. */
    #cells.-ai-debug Cell .ai-debug, #cells.-ai-debug Cell.-ai .debug-badge {
        display: block;
    }
    """
    BINDINGS = [
        Binding("ctrl+enter", "run_cell", "Run cell"),
        Binding("f5", "run_cell", "Run cell", show=False),
        Binding("ctrl+n", "new_cell", "New cell"),
        Binding("ctrl+d", "delete_cell", "Delete cell"),
        Binding("ctrl+j", "cycle_mode", "Cycle cell mode"),
        Binding("ctrl+o", "copy_output", "Copy output"),
        Binding("ctrl+g", "toggle_ai_debug", "AI debug"),
        Binding("ctrl+q", "quit", "Quit"),
    ]

    def __init__(self) -> None:
        super().__init__()
        self.kernel = Kernel()
        self.register_theme(EVERFOREST_DARK)
        self.theme = "everforest-dark"

    def compose(self) -> ComposeResult:
        yield Header()
        yield VerticalScroll(id="cells")
        yield Footer()

    async def on_mount(self) -> None:
        await self.add_cell(focus=True)

    async def add_cell(self, *, focus: bool = False, after: Cell | None = None, mode: str = "ai") -> Cell:
        cell = Cell(self.kernel)
        container = self.query_one("#cells", VerticalScroll)
        if after is None:
            await container.mount(cell)
        else:
            await container.mount(cell, after=after)
        # "python" (not ``mode``'s own default above) because that's what a
        # bare ``Cell(self.kernel)`` already constructs as -- see Cell.__init__
        # -- regardless of which mode is logically the app's default.
        if mode != "python":
            await cell.set_mode(mode)
        if focus:
            cell.editor.focus()
            cell.scroll_visible()
        return cell

    def _focused_cell(self) -> Cell | None:
        node = self.focused
        while node is not None and not isinstance(node, Cell):
            node = node.parent
        return node

    async def on_code_editor_submitted(self, _message: CodeEditor.Submitted) -> None:
        """Enter, in a single-line-submit editor (terminal-mode cells) -- run it."""
        await self.action_run_cell()

    async def action_run_cell(self) -> None:
        cell = self._focused_cell()
        if cell is None:
            return
        await cell.run_cell()
        if cell.shell_running:
            # A shell command still running (maybe waiting for input) --
            # focus stays on it; on_cell_shell_finished moves on once it's done.
            return
        await self._advance_from(cell)

    async def on_cell_shell_finished(self, message: Cell.ShellFinished) -> None:
        if message.had_focus and message.cell.is_attached:
            await self._advance_from(message.cell)

    async def _advance_from(self, cell: Cell) -> None:
        cells = list(self.query(Cell))
        if cell is cells[-1]:
            await self.add_cell(focus=True, mode=cell.mode)
        else:
            next_cell = cells[cells.index(cell) + 1]
            next_cell.editor.focus()
            next_cell.scroll_visible()

    async def action_new_cell(self) -> None:
        focused = self._focused_cell()
        mode = focused.mode if focused is not None else "ai"
        await self.add_cell(focus=True, after=focused, mode=mode)

    async def action_cycle_mode(self) -> None:
        cell = self._focused_cell()
        if cell is None:
            return
        await cell.cycle_mode()

    def action_copy_output(self) -> None:
        cell = self._focused_cell()
        if cell is not None:
            cell.copy_output()

    def action_toggle_ai_debug(self) -> None:
        """Show/hide the collapsible debug trace (tool calls, capability
        loads, retries) under every AI reply, plus a "debug" badge next to
        each AI cell's icon as the on/off indicator -- CSS-driven, see
        ``.ai-debug`` / ``.debug-badge`` in ``Cell.DEFAULT_CSS``.
        """
        self.query_one("#cells", VerticalScroll).toggle_class("-ai-debug")

    def action_delete_cell(self) -> None:
        cells = list(self.query(Cell))
        if len(cells) <= 1:
            return
        cell = self._focused_cell()
        if cell is None:
            return
        idx = cells.index(cell)
        cell.remove()
        remaining = cells[:idx] + cells[idx + 1 :]
        target = remaining[min(idx, len(remaining) - 1)]
        target.editor.focus()
        target.scroll_visible()


def main() -> None:
    NotebookApp().run()


if __name__ == "__main__":
    main()
