# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: copy plain text to the clipboard from inside the Textual app -- the OS clipboard tool
#          first (pbcopy / wl-copy / xclip / xsel / clip.exe), OSC 52 as the fallback.
# See spec/experimental/textual-kernel/portability.md ("clipboard") for why both are kept.
# ---------------------------------------------------------------------------
from __future__ import annotations

import os
import shutil
import subprocess

from textual.app import App

# In preference order; the first one on PATH that exits cleanly wins. Each
# fails fast (non-zero exit) when there's no display/session to talk to, eg
# wl-copy without WAYLAND_DISPLAY or xclip without DISPLAY.
_NATIVE_COMMANDS = (
    ("pbcopy",),
    ("wl-copy",),
    ("xclip", "-selection", "clipboard"),
    ("xsel", "--clipboard", "--input"),
    ("clip.exe",),
)


def _copy_via_native_command(text: str) -> bool:
    # Over SSH a native tool would "succeed" at filling the *remote* machine's
    # clipboard, not the user's -- OSC 52 is what reaches the local one there.
    if os.environ.get("SSH_CONNECTION"):
        return False
    for command in _NATIVE_COMMANDS:
        if shutil.which(command[0]) is None:
            continue
        try:
            # DEVNULL, not captured pipes: wl-copy/xclip fork a background
            # process that keeps serving the selection, and it would hold a
            # captured pipe open (hanging this call) until the next copy.
            subprocess.run(
                command,
                input=text.encode(),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=2,
                check=True,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        return True
    return False


def copy_text(app: App, text: str) -> None:
    """Put ``text`` on the clipboard: OS clipboard tool if one works, else OSC 52."""
    if not _copy_via_native_command(text):
        app.copy_to_clipboard(text)
