# AUTO-GENERATED by Claude Code
"""Jupyter-style rich display for a cell's return value.

``dataframe_view`` recognizes common dataframe types and returns plain
(columns, rows, total_row_count) data for the caller to feed into a Textual
``DataTable``. ``image_view`` recognizes a ``PIL.Image.Image`` and passes it
straight through for the caller to feed into ``textual_image``'s ``Image``
widget (see ``cell.py``), which itself picks the terminal's best available
graphics protocol (Kitty Graphics Protocol, Sixel, or a Unicode halfblock
fallback). ``markdown_segments`` does the same for an image reference
(``![alt](path-or-url)``) embedded inside a Markdown string -- e.g. an AI
reply -- since ``rich.markdown.Markdown`` itself never renders images, only
their alt text: a local path becomes an ``ImageRef``, an http(s) URL a
``RemoteImageRef`` for the caller to resolve with ``fetch_remote_image``.
``to_renderable`` is a fallback for objects that already implement Rich's
display protocol (e.g. a ``rich.table.Table`` built by hand); anything else
should just be shown via its repr().
"""

from __future__ import annotations

import io
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx2
from rich.console import RenderableType

if TYPE_CHECKING:
    from PIL.Image import Image as PILImage

MAX_ROWS = 500
MAX_COLS = 50

# Deliberately conservative -- ``fetch_remote_image`` downloads whatever
# URL happens to be sitting inside a model's own generated text, so this
# is untrusted input from the app's own point of view, not a URL the user
# typed themselves.
FETCH_TIMEOUT_SECONDS = 10.0
MAX_REMOTE_IMAGE_BYTES = 10 * 1024 * 1024

DataFrameView = tuple[list[str], list[tuple[Any, ...]], int]

# ``![alt](link)`` -- ``link`` captured whole (including an optional
# ``"title"`` after the path/URL, which real Markdown allows) since only
# the first whitespace-delimited token of it is actually the path/URL
# (see ``_classify_link``).
_MARKDOWN_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
_HTTP_URL_RE = re.compile(r"^https?://", re.IGNORECASE)


def to_renderable(value: Any) -> RenderableType | None:
    """Pass through objects that already implement Rich's display protocol."""
    if hasattr(value, "__rich_console__") or hasattr(value, "__rich__"):
        return value
    return None


def dataframe_view(value: Any) -> DataFrameView | None:
    """Return (columns, rows, total_row_count) for known dataframe types."""
    for builder in (_polars_view, _pandas_view):
        view = builder(value)
        if view is not None:
            return view
    return None


def _polars_view(value: Any) -> DataFrameView | None:
    try:
        import polars as pl
    except ImportError:
        return None

    if isinstance(value, pl.Series):
        value = value.to_frame()
    if not isinstance(value, pl.DataFrame):
        return None

    head = value.head(MAX_ROWS)
    columns = list(head.columns)[:MAX_COLS]
    rows = [tuple(_cell_str(v) for v in row[:MAX_COLS]) for row in head.rows()]
    return columns, rows, value.height


def _pandas_view(value: Any) -> DataFrameView | None:
    try:
        import pandas as pd
    except ImportError:
        return None

    if isinstance(value, pd.Series):
        value = value.to_frame()
    if not isinstance(value, pd.DataFrame):
        return None

    head = value.head(MAX_ROWS)
    columns = list(head.columns)[:MAX_COLS]
    rows = [
        tuple(_cell_str(v) for v in row[:MAX_COLS])
        for row in head.itertuples(index=False, name=None)
    ]
    return columns, rows, len(value)


def image_view(value: Any) -> PILImage | None:
    """Return ``value`` if it's a displayable image (currently: a
    ``PIL.Image.Image``), else ``None``.

    Pillow is a hard dependency of ``textual-image`` (not of this project
    directly), so unlike ``_polars_view``/``_pandas_view`` this import
    can't actually fail in practice -- the lazy try/except is kept anyway,
    for the same reason theirs is: this module shouldn't assume any one
    display library is installed.
    """
    try:
        from PIL import Image
    except ImportError:
        return None

    return value if isinstance(value, Image.Image) else None


@dataclass(frozen=True)
class ImageRef:
    """A ``![alt](path)`` match that resolved to a real local file."""

    alt: str
    path: Path


@dataclass(frozen=True)
class RemoteImageRef:
    """A ``![alt](url)`` match whose link is an http(s) URL.

    Left unresolved by ``markdown_segments`` itself (which does no I/O) --
    the caller awaits ``fetch_remote_image(ref.url)`` to actually get the
    image, so a slow/failed fetch is the caller's concern (e.g. showing a
    spinner, or falling back to plain text) rather than baked in here.
    """

    alt: str
    url: str


def markdown_segments(text: str) -> list[str | ImageRef | RemoteImageRef]:
    """Split ``text`` into alternating plain-Markdown-text chunks and
    ``ImageRef``/``RemoteImageRef``s, one per embedded ``![alt](link)``
    that resolves to either a real local file or an http(s) URL.

    The caller (``Cell._build_ai_reply_widgets``) renders each text chunk
    through ``rich.markdown.Markdown`` as before, each ``ImageRef``/
    resolved ``RemoteImageRef`` through ``textual_image``'s ``Image``
    widget, in order -- so a reply with a chart in the middle of it reads
    as prose, then image, then more prose, rather than one flat block with
    a broken-looking `![...]` line in it. A reference that isn't a local
    file or an http(s) URL (a path that doesn't exist, a `data:`/`ftp:`/
    other scheme) is left untouched inside its surrounding chunk -- Markdown
    itself already renders that fine as alt text.
    """
    segments: list[str | ImageRef | RemoteImageRef] = []
    last_end = 0

    for match in _MARKDOWN_IMAGE_RE.finditer(text):
        alt, link = match.group(1), match.group(2)
        ref = _classify_link(alt, link)
        if ref is None:
            continue

        if match.start() > last_end:
            segments.append(text[last_end : match.start()])
        segments.append(ref)
        last_end = match.end()

    if last_end < len(text):
        segments.append(text[last_end:])

    return segments


def _classify_link(alt: str, link: str) -> ImageRef | RemoteImageRef | None:
    # A titled link's content is `path/or/url "a title"` -- only the first
    # token is the actual path/URL.
    src = link.split(maxsplit=1)[0] if link.strip() else link

    if _HTTP_URL_RE.match(src):
        return RemoteImageRef(alt=alt, url=src)

    path = Path(src).expanduser()
    return ImageRef(alt=alt, path=path) if path.is_file() else None


async def fetch_remote_image(url: str) -> PILImage | None:
    """Best-effort fetch of an http(s) image URL for an AI reply's embedded
    ``![alt](https://...)`` reference.

    Deliberately cautious about what is, from this app's perspective,
    untrusted input (a URL chosen by the model, not typed by the user):
    a short timeout, a hard byte cap enforced while streaming (not just
    trusting a possibly-absent/-wrong Content-Length header), a bounded
    number of redirects, and the downloaded bytes must actually decode as
    an image via Pillow or this returns ``None`` -- same as a timeout or a
    404, for the caller to treat as "couldn't render this one" rather than
    showing something broken.
    """
    from PIL import Image, UnidentifiedImageError

    body = bytearray()
    try:
        async with httpx2.AsyncClient(
            timeout=FETCH_TIMEOUT_SECONDS, follow_redirects=True, max_redirects=3
        ) as client, client.stream("GET", url) as response:
            response.raise_for_status()
            async for chunk in response.aiter_bytes():
                body.extend(chunk)
                if len(body) > MAX_REMOTE_IMAGE_BYTES:
                    return None
    except httpx2.HTTPError:
        return None

    try:
        image = Image.open(io.BytesIO(bytes(body)))
        image.load()  # Image.open() is lazy -- force the actual decode now, inside this try.
    except (UnidentifiedImageError, OSError):
        return None
    return image


def _cell_str(value: Any) -> str:
    return "" if value is None else str(value)
