# AUTO-GENERATED by Claude Code
"""A persistent, in-process, Jupyter-like execution namespace.

Each ``run()`` call compiles and executes a chunk of code against a
namespace that persists across calls, mirroring how a Jupyter kernel keeps
variables alive between cells. If the last statement is a bare expression,
its repr is captured as "Out[n]" instead of being discarded, matching
IPython/Jupyter's interactive behavior.
"""

from __future__ import annotations

import ast
import contextlib
import io
import os
import sqlite3
import subprocess
import traceback
from dataclasses import dataclass
from typing import Any, Awaitable, Callable

import ds.ai

from . import sql

SHELL_TIMEOUT_SECONDS = 60

# subprocess.run's pipes aren't a tty, so most CLI tools' color "auto" mode
# (isatty() checks) silently disables itself -- these are the env vars tools
# commonly accept as an explicit override instead, so a shell cell's output
# still gets the same colors it would in a real terminal:
#   - CLICOLOR_FORCE/CLICOLOR: macOS/BSD ls, grep (what ships on this platform)
#   - FORCE_COLOR/COLORTERM: most Node-based and many Python/Rust/Go CLIs
#   - GIT_CONFIG_PARAMETERS: git has no single force-color env var, but this
#     injects a config value (here, color.ui=always) as if set in .gitconfig
# PAGER/GIT_PAGER/MANPAGER are pinned to `cat` because faking "this is a
# terminal" also makes git/man believe a pager is safe to launch -- with no
# real terminal attached to page through, that would just hang until
# SHELL_TIMEOUT_SECONDS instead of returning output.
_SHELL_COLOR_ENV = {
    "CLICOLOR_FORCE": "1",
    "CLICOLOR": "1",
    "FORCE_COLOR": "1",
    "COLORTERM": "truecolor",
    "GIT_CONFIG_PARAMETERS": "'color.ui=always'",
    "PAGER": "cat",
    "GIT_PAGER": "cat",
    "MANPAGER": "cat",
}


@dataclass
class CellResult:
    execution_count: int
    stdout: str = ""
    stderr: str = ""
    value: Any = None
    result_repr: str | None = None
    error: str | None = None


class Kernel:
    def __init__(self) -> None:
        self.namespace: dict[str, object] = {"__name__": "__console__"}
        self.execution_count = 0
        # In-memory, reseeded on every app start -- disposable, matching
        # this project's own "PoC, not production" stance. Held as a plain
        # DBAPI2 connection (see sql.py) so pointing this at a real database
        # later is a one-line swap, not a rewrite.
        self.sql_connection = sqlite3.connect(":memory:")
        sql.seed_sample_database(self.sql_connection)
        # pydantic-ai's own message objects, accumulated across ``run_ai``
        # calls (like ``namespace`` for Python) so later AI cells see the
        # full conversation so far, not just their own prompt.
        self.ai_history: list = []

    def sql_connection_info(self) -> tuple[str, str]:
        """``(engine, target)`` read straight off ``sql_connection`` itself
        (see ``sql.describe_connection``) -- surfaced by the UI (Cell's
        SQL-mode connection badge) so it's visible what a query is actually
        about to run against. Nothing to keep in sync by hand: swap
        ``sql_connection`` for a different driver later and this reflects
        it automatically.
        """
        return sql.describe_connection(self.sql_connection)

    def sql_schema(self) -> dict[str, list[str]]:
        """``{table: [column, ...]}`` read straight off ``sql_connection``
        (see ``sql.introspect_schema``) -- the candidate pool for SQL-mode
        completion (``sql_completion.py``). Re-queried on every call rather
        than cached: cheap against an in-memory sample database, and always
        reflects any DDL a cell has actually run.
        """
        return sql.introspect_schema(self.sql_connection)

    def run(self, code: str) -> CellResult:
        self.execution_count += 1
        result = CellResult(execution_count=self.execution_count)

        try:
            tree = ast.parse(code, mode="exec")
        except SyntaxError:
            result.error = traceback.format_exc()
            return result

        trailing_expr: ast.Expr | None = None
        if tree.body and isinstance(tree.body[-1], ast.Expr):
            trailing_expr = tree.body.pop()

        stdout, stderr = io.StringIO(), io.StringIO()
        try:
            with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                if tree.body:
                    exec(compile(tree, "<cell>", "exec"), self.namespace)
                if trailing_expr is not None:
                    value = eval(
                        compile(ast.Expression(trailing_expr.value), "<cell>", "eval"),
                        self.namespace,
                    )
                    if value is not None:
                        self.namespace["_"] = value
                        result.value = value
                        result.result_repr = repr(value)
        except Exception:
            result.error = traceback.format_exc()

        result.stdout = stdout.getvalue()
        result.stderr = stderr.getvalue()
        return result

    def run_shell(self, command: str) -> CellResult:
        """Run ``command`` in a subshell (IPython-style ``!`` escape).

        Not a persistent shell -- each call gets a fresh subprocess, so
        ``cd``/env var changes don't carry over between cells.
        """
        self.execution_count += 1
        result = CellResult(execution_count=self.execution_count)

        try:
            proc = subprocess.run(
                command,
                shell=True,
                capture_output=True,
                text=True,
                timeout=SHELL_TIMEOUT_SECONDS,
                env={**os.environ, **_SHELL_COLOR_ENV},
            )
            result.stdout = proc.stdout
            result.stderr = proc.stderr
            if proc.returncode != 0:
                result.error = f"[exit code {proc.returncode}]"
        except subprocess.TimeoutExpired:
            result.error = f"[timed out after {SHELL_TIMEOUT_SECONDS}s]"
        except OSError as exc:
            result.error = str(exc)

        return result

    def run_sql(self, query: str) -> CellResult:
        self.execution_count += 1
        result = CellResult(execution_count=self.execution_count)
        outcome = sql.execute(self.sql_connection, query)
        result.stdout = outcome.stdout
        result.value = outcome.value
        result.result_repr = outcome.result_repr
        result.error = outcome.error
        return result

    async def run_ai(
        self, prompt: str, *, on_delta: Callable[[str], Awaitable[None]] | None = None
    ) -> CellResult:
        """One turn of an AI chat cell, streamed from ``ds.ai.agent``.

        Async (unlike ``run``/``run_shell``/``run_sql``) since a real model
        call is network-latency-bound rather than near-instant -- awaiting
        it keeps the rest of the UI responsive while a response streams in
        server-side, instead of blocking Textual's event loop.

        ``on_delta``, if given, is awaited once per incremental text chunk
        as the reply streams in (``run_stream``/``stream_text(delta=True)``,
        pydantic-ai's own debouncing -- not every token individually) --
        the caller's hook for updating the cell's output live rather than
        only once the full reply has arrived. The final ``CellResult`` is
        still the source of truth for the cell's actual rendered output
        (see ``Cell._finish_run``); ``on_delta`` is purely a progress signal.
        """
        self.execution_count += 1
        result = CellResult(execution_count=self.execution_count)

        try:
            async with ds.ai.agent.run_stream(prompt, message_history=self.ai_history) as stream:
                async for delta in stream.stream_text(delta=True):
                    if on_delta is not None:
                        await on_delta(delta)
                output = await stream.get_output()
                self.ai_history = stream.all_messages()
        except Exception:
            result.error = traceback.format_exc()
            return result

        result.value = output
        result.result_repr = str(output)
        return result
