# AUTO-GENERATED by Claude Code
"""Renders a ``PIL.Image.Image`` in the terminal via Kitty's own Terminal
Graphics Protocol (https://sw.kovidgoyal.net/kitty/graphics-protocol/),
deliberately with no other protocol and no third-party terminal-graphics
library involved -- Ghostty (this app's actual target terminal) speaks
Kitty's protocol directly, so there's nothing an auto-detecting multi-
protocol library adds here except more code paths to go wrong in.

Technique: transmit the image once (chunked base64 PNG), then instead of
an absolutely-positioned overlay (which doesn't compose with a normal
character-grid renderer, and breaks under scrolling), draw a placement
using Kitty's "Unicode placeholder" trick -- a private-use codepoint
followed by row/column diacritics, styled with a foreground color that
encodes the image id. Kitty recognizes this exact pattern and paints the
image there instead of the literal glyphs. This is what lets image output
flow through Rich/Textual's ordinary Segment-based rendering (and scroll
correctly inside ``VerticalScroll`` along with everything else) rather
than needing a separate absolute-positioning/compositing system.

Sizing: the image is transmitted at its original resolution (downscaled
only if huge, purely to bound upload size -- see ``_MAX_TRANSMIT_SIDE``)
and the placement is given a target column/row count; Kitty itself scales
to fit that box terminal-side. This avoids needing this module to query
the terminal's own cell pixel size (an ioctl call with no real risk, but
one more thing to get right) just to pre-scale client-side -- letting the
already-battle-tested terminal-side scaler do that job instead.
"""

from __future__ import annotations

import io
import os
import sys
from base64 import b64encode
from itertools import count
from pathlib import Path
from random import randint
from typing import IO, Callable

from PIL import Image as PILImage
from rich.style import Style
from rich.text import Text
from textual.widget import Widget

_TGP_START = "\x1b_G"
_TGP_END = "\x1b\\"
_CHUNK_SIZE = 4096

# Kitty's Unicode-placeholder scheme (protocol-mandated values, not a
# stylistic choice -- see "Unicode placeholders" in the protocol docs
# linked above). Reproduced verbatim rather than derived.
_PLACEHOLDER = chr(0x10EEEE)
# fmt: off
_NUMBER_TO_DIACRITIC = [
     0x00305, 0x0030d, 0x0030e, 0x00310, 0x00312, 0x0033d, 0x0033e, 0x0033f, 0x00346, 0x0034a, 0x0034b, 0x0034c,
     0x00350, 0x00351, 0x00352, 0x00357, 0x0035b, 0x00363, 0x00364, 0x00365, 0x00366, 0x00367, 0x00368, 0x00369,
     0x0036a, 0x0036b, 0x0036c, 0x0036d, 0x0036e, 0x0036f, 0x00483, 0x00484, 0x00485, 0x00486, 0x00487, 0x00592,
     0x00593, 0x00594, 0x00595, 0x00597, 0x00598, 0x00599, 0x0059c, 0x0059d, 0x0059e, 0x0059f, 0x005a0, 0x005a1,
     0x005a8, 0x005a9, 0x005ab, 0x005ac, 0x005af, 0x005c4, 0x00610, 0x00611, 0x00612, 0x00613, 0x00614, 0x00615,
     0x00616, 0x00617, 0x00657, 0x00658, 0x00659, 0x0065a, 0x0065b, 0x0065d, 0x0065e, 0x006d6, 0x006d7, 0x006d8,
     0x006d9, 0x006da, 0x006db, 0x006dc, 0x006df, 0x006e0, 0x006e1, 0x006e2, 0x006e4, 0x006e7, 0x006e8, 0x006eb,
     0x006ec, 0x00730, 0x00732, 0x00733, 0x00735, 0x00736, 0x0073a, 0x0073d, 0x0073f, 0x00740, 0x00741, 0x00743,
     0x00745, 0x00747, 0x00749, 0x0074a, 0x007eb, 0x007ec, 0x007ed, 0x007ee, 0x007ef, 0x007f0, 0x007f1, 0x007f3,
     0x00816, 0x00817, 0x00818, 0x00819, 0x0081b, 0x0081c, 0x0081d, 0x0081e, 0x0081f, 0x00820, 0x00821, 0x00822,
     0x00823, 0x00825, 0x00826, 0x00827, 0x00829, 0x0082a, 0x0082b, 0x0082c, 0x0082d, 0x00951, 0x00953, 0x00954,
     0x00f82, 0x00f83, 0x00f86, 0x00f87, 0x0135d, 0x0135e, 0x0135f, 0x017dd, 0x0193a, 0x01a17, 0x01a75, 0x01a76,
     0x01a77, 0x01a78, 0x01a79, 0x01a7a, 0x01a7b, 0x01a7c, 0x01b6b, 0x01b6d, 0x01b6e, 0x01b6f, 0x01b70, 0x01b71,
     0x01b72, 0x01b73, 0x01cd0, 0x01cd1, 0x01cd2, 0x01cda, 0x01cdb, 0x01ce0, 0x01dc0, 0x01dc1, 0x01dc3, 0x01dc4,
     0x01dc5, 0x01dc6, 0x01dc7, 0x01dc8, 0x01dc9, 0x01dcb, 0x01dcc, 0x01dd1, 0x01dd2, 0x01dd3, 0x01dd4, 0x01dd5,
     0x01dd6, 0x01dd7, 0x01dd8, 0x01dd9, 0x01dda, 0x01ddb, 0x01ddc, 0x01ddd, 0x01dde, 0x01ddf, 0x01de0, 0x01de1,
     0x01de2, 0x01de3, 0x01de4, 0x01de5, 0x01de6, 0x01dfe, 0x020d0, 0x020d1, 0x020d4, 0x020d5, 0x020d6, 0x020d7,
     0x020db, 0x020dc, 0x020e1, 0x020e7, 0x020e9, 0x020f0, 0x02cef, 0x02cf0, 0x02cf1, 0x02de0, 0x02de1, 0x02de2,
     0x02de3, 0x02de4, 0x02de5, 0x02de6, 0x02de7, 0x02de8, 0x02de9, 0x02dea, 0x02deb, 0x02dec, 0x02ded, 0x02dee,
     0x02def, 0x02df0, 0x02df1, 0x02df2, 0x02df3, 0x02df4, 0x02df5, 0x02df6, 0x02df7, 0x02df8, 0x02df9, 0x02dfa,
     0x02dfb, 0x02dfc, 0x02dfd, 0x02dfe, 0x02dff, 0x0a66f, 0x0a67c, 0x0a67d, 0x0a6f0, 0x0a6f1, 0x0a8e0, 0x0a8e1,
     0x0a8e2, 0x0a8e3, 0x0a8e4, 0x0a8e5, 0x0a8e6, 0x0a8e7, 0x0a8e8, 0x0a8e9, 0x0a8ea, 0x0a8eb, 0x0a8ec, 0x0a8ed,
     0x0a8ee, 0x0a8ef, 0x0a8f0, 0x0a8f1, 0x0aab0, 0x0aab2, 0x0aab3, 0x0aab7, 0x0aab8, 0x0aabe, 0x0aabf, 0x0aac1,
     0x0fe20, 0x0fe21, 0x0fe22, 0x0fe23, 0x0fe24, 0x0fe25, 0x0fe26, 0x10a0f, 0x10a38, 0x1d185, 0x1d186, 0x1d187,
     0x1d188, 0x1d189, 0x1d1aa, 0x1d1ab, 0x1d1ac, 0x1d1ad, 0x1d242, 0x1d243, 0x1d244,
]
# fmt: on

# Bandwidth safeguard only (not needed for correct scaling -- see module
# docstring): a source image larger than this on either side is
# downsampled before transmission, nothing more.
_MAX_TRANSMIT_SIDE = 2000

# Best-effort unique-enough image ids: random start, incrementing, entirely
# client-side. We can't read the terminal's own id-allocation responses
# back to confirm -- Textual owns stdin with its own reader thread, so
# nothing in this process can safely read a terminal response once the app
# has started (see the module docstring on why this can't just ask the
# terminal to pick one for us).
_image_id_counter = count(randint(1, 2**31))

_IS_TMUX = bool(os.environ.get("TMUX"))


def _write(sequence: str) -> None:
    stdout = sys.__stdout__
    if stdout is None or not stdout.isatty():
        return
    if _IS_TMUX:
        # tmux passthrough DCS envelope: wrap the whole sequence, and
        # double any ESC bytes inside it (tmux's own passthrough syntax).
        sequence = "\x1bPtmux;" + sequence.replace("\x1b", "\x1b\x1b") + "\x1b\\"
    stdout.write(sequence)
    stdout.flush()


def _send(payload: str | None = None, **control: int | str | None) -> None:
    fields = ",".join(f"{k}={v}" for k, v in control.items() if v is not None)
    _write(f"{_TGP_START}{fields}{';' + payload if payload else ''}{_TGP_END}")


def _transmit(image: PILImage.Image, image_id: int) -> None:
    if image.width > _MAX_TRANSMIT_SIDE or image.height > _MAX_TRANSMIT_SIDE:
        image = image.copy()
        image.thumbnail((_MAX_TRANSMIT_SIDE, _MAX_TRANSMIT_SIDE), PILImage.Resampling.LANCZOS)

    buf = io.BytesIO()
    image.convert("RGBA").save(buf, format="PNG", compress_level=2)
    data = b64encode(buf.getvalue()).decode("ascii")

    while data:
        chunk, data = data[:_CHUNK_SIZE], data[_CHUNK_SIZE:]
        # f=100: PNG payload (Kitty decodes it itself, no raw-pixel-format
        # bookkeeping on our side). q=2: suppress every response -- we
        # have no safe way to read one back once Textual owns stdin.
        _send(payload=chunk, i=image_id, m=1 if data else 0, f=100, q=2)


def _place(image_id: int, columns: int, rows: int) -> None:
    # p=1: a fixed placement id, not left to the terminal to pick one. Some
    # terminals -- Ghostty included, per a real reported case -- only
    # replace the image *data* on a re-transmit of the same image id and
    # leave a previous unnamed placement dangling rather than replacing it
    # too; naming it explicitly sidesteps that rather than depending on it.
    _send(a="p", i=image_id, p=1, c=columns, r=rows, U=1, q=2)


def _delete(image_id: int) -> None:
    _send(a="d", i=image_id, p=1, q=2)


def _fit_cells(image_width: int, image_height: int, max_cols: int, max_rows: int) -> tuple[int, int]:
    """Largest (cols, rows) within (max_cols, max_rows) that keeps the
    image's own aspect ratio, given a typical monospace cell's pixel
    proportions (roughly twice as tall as wide -- close enough for this
    without querying the terminal's actual cell pixel size, which would
    need the same raw-stdin access this module otherwise avoids)."""
    if max_cols <= 0 or max_rows <= 0 or image_width <= 0 or image_height <= 0:
        return 0, 0

    cell_aspect = 0.5  # assumed cell width / cell height
    rows_for_full_width = max(1, round(max_cols * cell_aspect * image_height / image_width))
    if rows_for_full_width <= max_rows:
        return max_cols, rows_for_full_width

    cols_for_full_height = max(1, round(max_rows * image_width / (cell_aspect * image_height)))
    return min(cols_for_full_height, max_cols), max_rows


class KittyImage(Widget):
    """Displays a PIL image (or a path to one) via Kitty's Terminal
    Graphics Protocol. Renders nothing on a terminal that doesn't speak
    that protocol -- see the module docstring for why this deliberately
    doesn't fall back to Sixel/halfblocks/etc.

    Deliberately no ``content-align``/padding CSS: the placeholder
    technique this renders with (see module docstring) depends on each
    placeholder character landing at an *exact* cell offset from the
    placement's own top-left -- anything that pads or re-centers the
    rendered text within the widget's box would shift those offsets
    relative to what the row/column diacritics actually encode.
    """

    def __init__(
        self,
        image: str | Path | IO[bytes] | PILImage.Image,
        *,
        on_error: Callable[[Exception], Widget] | None = None,
        name: str | None = None,
        id: str | None = None,  # noqa: A002 -- matches Widget's own param name
        classes: str | None = None,
        disabled: bool = False,
    ) -> None:
        super().__init__(name=name, id=id, classes=classes, disabled=disabled)
        self._image: PILImage.Image | None = None
        self._error_widget: Widget | None = None
        self._image_id: int | None = None
        self._placed_size: tuple[int, int] | None = None
        self._cached_render: Text | None = None

        try:
            self._image = image if isinstance(image, PILImage.Image) else PILImage.open(image)
        except Exception as exc:  # noqa: BLE001 -- reported via on_error, not swallowed
            if on_error is None:
                raise
            self._error_widget = on_error(exc)

    def compose(self):
        if self._error_widget is not None:
            yield self._error_widget

    def on_unmount(self) -> None:
        if self._image_id is not None:
            _delete(self._image_id)
            self._image_id = None

    def render(self) -> Text | str:
        if self._image is None:
            return ""

        size = self.size
        if size.width <= 0 or size.height <= 0:
            return ""

        if self._image_id is None:
            self._image_id = next(_image_id_counter)
            _transmit(self._image, self._image_id)

        if self._cached_render is None or self._placed_size != (size.width, size.height):
            self._placed_size = (size.width, size.height)
            cols, rows = _fit_cells(self._image.width, self._image.height, size.width, size.height)
            _place(self._image_id, cols, rows)
            self._cached_render = _build_placeholder_text(self._image_id, cols, rows)

        return self._cached_render


def _build_placeholder_text(image_id: int, cols: int, rows: int) -> Text:
    style = Style(color=f"rgb({(image_id >> 16) & 255},{(image_id >> 8) & 255},{image_id & 255})")
    id_diacritic = chr(_NUMBER_TO_DIACRITIC[(image_id >> 24) & 255])
    lines = [
        "".join(f"{_PLACEHOLDER}{chr(_NUMBER_TO_DIACRITIC[r])}{chr(_NUMBER_TO_DIACRITIC[c])}{id_diacritic}" for c in range(cols))
        for r in range(rows)
    ]
    return Text("\n".join(lines), style=style, no_wrap=True)
