# AUTO-GENERATED by Claude Code
"""A persistent bash session on a pseudo-terminal, for shell-mode cells.

One long-lived ``bash`` per kernel (like one Python namespace per kernel), so
``cd``, ``export``, shell variables and functions carry over between cells.
Commands run with the pty as their controlling terminal and stdin, so they
behave as they would in a real terminal: tools color their own output, and
anything that reads from the terminal (``sudo``'s password prompt, a
``[Y/n]`` confirmation, ``read``) can be answered through ``send_input``.

Two channels, deliberately separate:

- **commands** go to bash's stdin, a plain pipe that only bash reads -- each
  one is run as ``eval '<command>' </dev/tty`` (inside a function, see
  ``_start``), so the command itself reads
  from the terminal and can never swallow the *next* queued command as input.
- **output** (stdout and stderr merged, as in a real terminal) comes back
  from the pty's master side, followed by a per-run marker (an OSC escape
  sequence carrying a random token, the exit status and ``$PWD``) that says
  the command finished. The marker is stripped before output reaches
  ``on_output``.

POSIX only (``pty``/``termios``): ``PTY_SUPPORTED`` is False on Windows,
where ``Kernel`` falls back to one plain subprocess per command.
"""

from __future__ import annotations

import asyncio
import codecs
import os
import re
import secrets
import shlex
import shutil
import struct
import subprocess
import sys
from collections.abc import Awaitable, Callable

PTY_SUPPORTED = sys.platform != "win32"

if PTY_SUPPORTED:
    import fcntl
    import pty
    import termios

_CTRL_C = b"\x03"
_CTRL_D = b"\x04"


def _take_controlling_tty() -> None:
    """``preexec_fn``: runs in the child after ``start_new_session`` has made
    it a session leader, and after its stdout was pointed at the pty -- so fd
    1 is the pty slave, and claiming it as the controlling terminal makes
    ``/dev/tty`` (what ``eval ... </dev/tty`` and ``sudo`` open) resolve to it.
    """
    fcntl.ioctl(1, termios.TIOCSCTTY, 0)


class ShellSession:
    def __init__(self, env: dict[str, str], cwd: str | None = None) -> None:
        self._env = env
        self._proc: subprocess.Popen | None = None
        self._master: int | None = None
        self._lock = asyncio.Lock()
        self.cwd = cwd or os.getcwd()
        """Last known working directory -- read from each run's marker, and
        where a new bash starts if the old one exited (eg a cell ran ``exit``)."""

    @property
    def is_alive(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def _start(self) -> None:
        master, slave = pty.openpty()
        attrs = termios.tcgetattr(slave)
        # No "\n" -> "\r\n" translation on output: output is displayed as a
        # scrollback log, where a bare "\r" means "overwrite this line" (how
        # progress bars redraw) rather than a line ending.
        attrs[1] &= ~termios.ONLCR
        termios.tcsetattr(slave, termios.TCSANOW, attrs)
        # Tools that size their output to the terminal (progress bars,
        # column layouts) read this; the notebook's own width, minus the
        # cell's gutter, is the closest real answer.
        columns, rows = shutil.get_terminal_size((120, 40))
        fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", rows, max(40, columns - 8), 0, 0))

        self._proc = subprocess.Popen(
            ["bash", "--noprofile", "--norc"],
            stdin=subprocess.PIPE,
            stdout=slave,
            stderr=slave,
            cwd=self.cwd if os.path.isdir(self.cwd) else None,
            env=self._env,
            start_new_session=True,
            preexec_fn=_take_controlling_tty,
        )
        os.close(slave)
        os.set_blocking(master, False)
        self._master = master
        # Ctrl+C (``interrupt``) sends SIGINT to everything in the terminal's
        # foreground process group, bash included. A non-interactive bash
        # would exit on it; this trap instead returns from ``__tk_run`` (the
        # function every command runs inside), abandoning the rest of the
        # command like a real terminal does, with the usual 130 status --
        # and the session (and its cwd/env) survives. A trap -- unlike
        # ``trap '' INT`` -- is reset on exec, so commands still get the
        # default SIGINT behavior and actually stop.
        self._write_command('__tk_run() { eval "$1" </dev/tty; }')
        self._write_command("trap 'return 130 2>/dev/null' INT")

    def _write_command(self, line: str) -> None:
        assert self._proc is not None and self._proc.stdin is not None
        self._proc.stdin.write((line + "\n").encode())
        self._proc.stdin.flush()

    def _close(self) -> None:
        if self._master is not None:
            os.close(self._master)
            self._master = None
        if self._proc is not None:
            if self._proc.poll() is None:
                self._proc.kill()
            self._proc.wait()
            self._proc = None

    async def run(
        self, command: str, *, on_output: Callable[[str], Awaitable[None]] | None = None
    ) -> tuple[str, int | None]:
        """Run ``command`` in the session; returns ``(output, exit_status)``.

        ``exit_status`` is None if bash itself exited mid-command (a cell ran
        ``exit``) -- the next run then starts a fresh bash in ``self.cwd``.
        Runs are serialized: a second cell's command waits for the first.
        """
        async with self._lock:
            if not self.is_alive:
                self._close()
                self._start()
            assert self._master is not None
            master = self._master

            token = secrets.token_hex(8)
            marker = f"\x1b]tk-done;{token};"
            marker_re = re.compile(re.escape(marker) + r"(\d+);(.*?)\x07", re.DOTALL)
            decoder = codecs.getincrementaldecoder("utf-8")(errors="replace")
            loop = asyncio.get_running_loop()
            chunks: asyncio.Queue[str | None] = asyncio.Queue()

            def on_readable() -> None:
                try:
                    data = os.read(master, 65536)
                except BlockingIOError:
                    return
                except OSError:  # EIO: every slave fd closed, ie bash exited
                    data = b""
                if data:
                    chunks.put_nowait(decoder.decode(data))
                else:
                    loop.remove_reader(master)
                    chunks.put_nowait(None)

            loop.add_reader(master, on_readable)
            output = ""
            pending = ""
            status: int | None = None
            try:
                self._write_command(
                    f'__tk_run {shlex.quote(command)}; printf \'\\033]tk-done;{token};%s;%s\\007\' "$?" "$PWD"'
                )
                while True:
                    chunk = await chunks.get()
                    if chunk is None:
                        emit, pending = pending, ""
                    else:
                        pending += chunk
                        match = marker_re.search(pending)
                        if match:
                            emit = pending[: match.start()]
                            status = int(match.group(1))
                            self.cwd = match.group(2)
                        else:
                            emit, pending = _split_before_partial(pending, marker)
                    emit = emit.replace("\r\n", "\n")
                    if emit:
                        output += emit
                        if on_output is not None:
                            await on_output(emit)
                    if chunk is None or status is not None:
                        break
            except asyncio.CancelledError:
                # The cell was deleted mid-run -- stop the command rather than
                # leave it holding the session (and the next run's lock).
                self.interrupt()
                raise
            finally:
                if self._master == master:
                    loop.remove_reader(master)
            return output, status

    def send_input(self, text: str) -> None:
        """Type ``text`` into the terminal, as if at the keyboard."""
        if self._master is not None:
            os.write(self._master, text.encode())

    def send_eof(self) -> None:
        if self._master is not None:
            os.write(self._master, _CTRL_D)

    def interrupt(self) -> None:
        """Ctrl+C: the terminal itself turns this into SIGINT for the
        running command (same as pressing it in a real terminal).
        """
        if self._master is not None:
            os.write(self._master, _CTRL_C)

    def input_is_hidden(self) -> bool:
        """True while the terminal has echo turned off -- what ``sudo``,
        ``ssh``, ``read -s`` etc. do when asking for a password, so the UI can
        mask what's typed without having to recognize every prompt's wording.
        """
        if self._master is None:
            return False
        try:
            return not termios.tcgetattr(self._master)[3] & termios.ECHO
        except termios.error:
            return False


def _split_before_partial(text: str, marker: str) -> tuple[str, str]:
    """Split off a tail of ``text`` that could be the start of ``marker`` (or
    an incomplete marker), so a marker split across two reads never leaks
    into the output. Returns ``(safe_to_emit, hold_back)``.
    """
    index = text.find(marker)
    if index != -1:
        return text[:index], text[index:]
    for size in range(min(len(marker) - 1, len(text)), 0, -1):
        if text.endswith(marker[:size]):
            return text[:-size], text[-size:]
    return text, ""
