# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: Print a player's character and starter/counterpick stage usage from their
# supermajor.gg page (via ds.data.raw.supermajor).
#
# Example CLI Commands:
#   1. Last 6 Months:   uv run scripts/supermajor_usage.py "https://www.supermajor.gg/ultimate/player/DeLulu?id=S4734338"
#   2. All Time:        uv run scripts/supermajor_usage.py "<player url>" --all-time
#   3. Raw JSON:        uv run scripts/supermajor_usage.py "<player url>" --json
# ---------------------------------------------------------------------------
from __future__ import annotations

from typing import Annotated

import typer
from ds.data.raw.supermajor import ALL_TIME, LAST_6_MONTHS, StageStats, player_usage
from rich import print as rprint

app = typer.Typer()


def _print_stages(title: str, stats: StageStats) -> None:
    rprint(f"\n[bold]{title}[/bold] ({stats.games} games)")
    for s in stats.stages:
        rprint(f"  {s.stage:<20} {s.usage_pct:5.1f}%  ({s.games} games)")


@app.command()
def main(
    url: Annotated[str, typer.Argument(help="supermajor.gg player page url")],
    all_time: Annotated[bool, typer.Option("--all-time", help="All Time instead of Last 6 Months")] = False,
    as_json: Annotated[bool, typer.Option("--json", help="Print the PlayerUsage model as JSON")] = False,
) -> None:
    """Print each character's and stage's usage % for a supermajor.gg player."""
    usage = player_usage(url, ALL_TIME if all_time else LAST_6_MONTHS)
    if as_json:
        rprint(usage.model_dump_json(indent=2))
        return
    rprint(f"[bold]Characters[/bold] ({usage.period})")
    for c in usage.characters:
        rprint(f"  {c.character:<20} {c.usage_pct:5.1f}%  ({c.games} games)")
    _print_stages("Starters", usage.starters)
    _print_stages("Counterpicks", usage.counters)


if __name__ == "__main__":
    app()
