# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: read labelled MyST list-tables from docs/ as polars DataFrames, so code built on
#          docs facts can be sync-tested against them (eg tests/ds/calc/test_stale.py).
# Usage: docs_table("stale-reductors") -> DataFrame of that table (cells as plain strings)
# ---------------------------------------------------------------------------
from __future__ import annotations

import re
from typing import TYPE_CHECKING

import polars as pl

from ds.util.const import REPO_DIR

if TYPE_CHECKING:
    from pathlib import Path

__all__ = ["DOCS_DIR", "docs_table"]

DOCS_DIR = REPO_DIR / "docs"
# build output (copies of every page) and local test pages
_SKIPPED_DIRS = {"_build", "local"}

_FENCE_RE = re.compile(r"^(`{3,}|:{3,})\{list-table\}")


def _plain(cell: str) -> str:
    """Drop inline markdown emphasis/code markers and collapse whitespace."""
    return " ".join(cell.replace("`", "").replace("**", "").split())


def _find(label: str, files: list[Path]) -> tuple[Path, list[str]]:
    matches = []
    for file in files:
        lines = file.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            if line.strip() == f":label: {label}":
                matches.append((file, lines, i))
    if not matches:
        raise KeyError(f"no list-table labelled {label!r} under {DOCS_DIR}")
    if len(matches) > 1:
        raise KeyError(f"list-table label {label!r} is used more than once: {[str(m[0]) for m in matches]}")
    file, lines, label_idx = matches[0]
    start = next(i for i in range(label_idx, -1, -1) if _FENCE_RE.match(lines[i]))
    fence = _FENCE_RE.match(lines[start]).group(1)
    end = next(i for i in range(label_idx + 1, len(lines)) if lines[i].strip() == fence)
    return file, lines[start + 1 : end]


def docs_table(label: str, *, plain: bool = True) -> pl.DataFrame:
    """The MyST list-table with `:label: <label>` anywhere under docs/, one row per table row.

    Uses the first row as column names when the table has `:header-rows: 1`, otherwise columns
    are named column_1, column_2, ... All cells are strings.

    Args:
        label: the table's `:label:` value, eg 'stale-reductors'.
        plain: strip backticks and bold markers from cells (eg '`0.09`' -> '0.09').
    """
    files = [f for f in sorted(DOCS_DIR.rglob("*.md")) if not _SKIPPED_DIRS.intersection(f.relative_to(DOCS_DIR).parts)]
    _, body = _find(label, files)
    header_rows = 0
    rows: list[list[str]] = []
    for line in body:
        if m := re.match(r"^:header-rows:\s*(\d+)", line):
            header_rows = int(m.group(1))
        elif line.startswith("* - "):
            rows.append([line[4:]])
        elif line.startswith("  - ") and rows:
            rows[-1].append(line[4:])
        elif line.startswith("    ") and rows:  # wrapped continuation of the current cell
            rows[-1][-1] += " " + line.strip()
    if plain:
        rows = [[_plain(c) for c in row] for row in rows]
    if header_rows:
        columns, rows = rows[0], rows[header_rows:]
    else:
        columns = [f"column_{i}" for i in range(1, max(map(len, rows), default=0) + 1)]
    return pl.DataFrame(rows, schema={c: pl.String for c in columns}, orient="row")
