#!/usr/bin/env bash
set -euo pipefail

# AUTO-GENERATED by GitHub Copilot
# Purpose: Toggle region recording on Omarchy/Hyprland using one script for start/stop.
# Output: Clipboard mode uses temp .mp4 and auto-cleans; save mode keeps clips in local/assets/snippets.
# Usage: SUPER+SHIFT+Q for clipboard mode, SUPER+SHIFT+ALT+Q for --save mode.
# Requires: wf-recorder, slurp, notify-send, and wl-copy (or xclip fallback).
TMP_DIR="${XDG_RUNTIME_DIR:-/tmp}/screenrecord"
SAVE_DIR="$HOME/repos/delulu-smash/local/assets/snippets"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/screenrecord"
STATE_FILE="$STATE_DIR/current_recording.txt"

MODE="clipboard"
if [[ "${1:-}" == "--save" ]]; then
    MODE="save"
fi

mkdir -p "$TMP_DIR" "$SAVE_DIR" "$STATE_DIR"

copy_clip_video() {
    local file_path="$1"

    if command -v wl-copy >/dev/null 2>&1; then
        wl-copy --type video/mp4 < "$file_path"
        return 0
    fi

    if command -v xclip >/dev/null 2>&1; then
        xclip -selection clipboard -t video/mp4 < "$file_path"
        return 0
    fi

    return 1
}

copy_clip_path() {
    local file_path="$1"
    local file_uri="file://$file_path"

    if command -v wl-copy >/dev/null 2>&1; then
        printf '%s\n' "$file_uri" | wl-copy --type text/uri-list
        return 0
    fi

    if command -v xclip >/dev/null 2>&1; then
        printf '%s\n' "$file_uri" | xclip -selection clipboard -t text/uri-list
        return 0
    fi

    return 1
}

for cmd in wf-recorder slurp notify-send; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Missing dependency: $cmd" >&2
        notify-send "Screen Recorder" "Missing dependency: $cmd" -i dialog-error || true
        exit 1
    fi
done

if pgrep -x wf-recorder >/dev/null 2>&1; then
    # Stop current recording.
    pkill -INT -x wf-recorder || true

    if [[ -f "$STATE_FILE" ]]; then
        STATE_CONTENT=$(cat "$STATE_FILE")
        if [[ "$STATE_CONTENT" == *$'\t'* ]]; then
            RECORD_MODE=${STATE_CONTENT%%$'\t'*}
            LAST_FILE=${STATE_CONTENT#*$'\t'}
        else
            # Backward compatibility with old state format that stored only file path.
            RECORD_MODE="clipboard"
            LAST_FILE="$STATE_CONTENT"
        fi

        if [[ "$RECORD_MODE" == "save" ]]; then
            if copy_clip_path "$LAST_FILE"; then
                notify-send "Screen Recorder" "Saved clip and copied file reference: $(basename "$LAST_FILE")" -i video-x-generic
            else
                notify-send "Screen Recorder" "Saved clip: $(basename "$LAST_FILE")" -i video-x-generic
            fi
        else
            if copy_clip_video "$LAST_FILE"; then
                # Keep this workflow paste-ready while avoiding accumulated saved files.
                rm -f "$LAST_FILE"
                notify-send "Screen Recorder" "Copied clip to clipboard (temporary file removed)" -i video-x-generic
            else
                FALLBACK_FILE="$SAVE_DIR/$(basename "$LAST_FILE")"
                mv "$LAST_FILE" "$FALLBACK_FILE"
                notify-send "Screen Recorder" "Clipboard copy failed; clip kept at $(basename "$FALLBACK_FILE")" -i video-x-generic
            fi
        fi
        rm -f "$STATE_FILE"
    else
        notify-send "Screen Recorder" "Recording stopped" -i video-x-generic
    fi
    exit 0
fi

GEOMETRY=$(slurp -b 000000a0 -c 00aaffff -w 2)
if [[ -z "$GEOMETRY" ]]; then
    exit 0
fi

TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
if [[ "$MODE" == "save" ]]; then
    OUTPUT_FILE="$SAVE_DIR/snippet_$TIMESTAMP.mp4"
else
    OUTPUT_FILE="$TMP_DIR/snippet_$TIMESTAMP.mp4"
fi
printf '%s\t%s\n' "$MODE" "$OUTPUT_FILE" > "$STATE_FILE"

notify-send "Screen Recorder" "Recording started" -i video-x-generic

# Run detached so keybind can trigger this script again to stop recording.
nohup wf-recorder -g "$GEOMETRY" -f "$OUTPUT_FILE" >/dev/null 2>&1 &