#!/usr/bin/env bash
set -euo pipefail

# AUTO-GENERATED by GitHub Copilot
# Purpose: Toggle region recording on Omarchy/Hyprland using one script for start/stop.
# Output: Clipboard mode converts to .gif and auto-cleans; save mode keeps .mp4 clips in local/assets/snippets.
# Usage: SUPER+SHIFT+Q for clipboard mode (gif default), SUPER+SHIFT+ALT+Q for --save mode.
# Run: $HOME/repos/delulu-smash/.os/screenrecord.sh [--gif|--mp4|--save]
# Requires: wf-recorder, slurp, notify-send, ffmpeg, and wl-copy (or xclip fallback).
TMP_DIR="${XDG_RUNTIME_DIR:-/tmp}/screenrecord"
SAVE_DIR="$HOME/repos/delulu-smash/local/assets/snippets"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/screenrecord"
STATE_FILE="$STATE_DIR/current_recording.txt"
# Will delete file after 180 seconds (ensure can copy to clipboard)
CLEANUP_AFTER_SECONDS="${SCREENRECORD_CLIPBOARD_TTL_SECONDS:-180}"

MODE="clipboard"
CLIPBOARD_FORMAT="${SCREENRECORD_CLIPBOARD_FORMAT:-gif}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --save)
            MODE="save"
            ;;
        --gif)
            CLIPBOARD_FORMAT="gif"
            ;;
        --mp4)
            CLIPBOARD_FORMAT="mp4"
            ;;
        --format=gif)
            CLIPBOARD_FORMAT="gif"
            ;;
        --format=mp4)
            CLIPBOARD_FORMAT="mp4"
            ;;
        *)
            notify-send "Screen Recorder" "Unsupported option: $1" -i dialog-error || true
            exit 1
            ;;
    esac
    shift
done

if [[ "$CLIPBOARD_FORMAT" != "gif" && "$CLIPBOARD_FORMAT" != "mp4" ]]; then
    notify-send "Screen Recorder" "Invalid format: $CLIPBOARD_FORMAT (use gif or mp4)" -i dialog-error || true
    exit 1
fi

mkdir -p "$TMP_DIR" "$SAVE_DIR" "$STATE_DIR"

copy_clip_video() {
    local file_path="$1"

    if command -v wl-copy >/dev/null 2>&1; then
        wl-copy --type video/mp4 < "$file_path"
        return 0
    fi

    if command -v xclip >/dev/null 2>&1; then
        xclip -selection clipboard -t video/mp4 < "$file_path"
        return 0
    fi

    return 1
}

copy_clip_gif() {
    local file_path="$1"

    if command -v wl-copy >/dev/null 2>&1; then
        wl-copy --type image/gif < "$file_path"
        return 0
    fi

    if command -v xclip >/dev/null 2>&1; then
        xclip -selection clipboard -t image/gif < "$file_path"
        return 0
    fi

    return 1
}

convert_mp4_to_gif() {
    local input_file="$1"
    local output_file="$2"
    local fps="${SCREENRECORD_GIF_FPS:-12}"
    local width="${SCREENRECORD_GIF_WIDTH:-960}"

    # Two-pass palette approach: generate an optimised 256-colour palette from the
    # actual video frames, then use it for conversion. Avoids blotchy dithering.
    local palette_file
    palette_file=$(mktemp --suffix=.png)
    ffmpeg -y -loglevel error -i "$input_file" \
        -vf "fps=${fps},scale=${width}:-1:flags=lanczos,palettegen=stats_mode=diff" \
        "$palette_file" || { rm -f "$palette_file"; return 1; }
    ffmpeg -y -loglevel error -i "$input_file" -i "$palette_file" \
        -lavfi "fps=${fps},scale=${width}:-1:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" \
        "$output_file"
    local status=$?
    rm -f "$palette_file"
    return $status
}

schedule_cleanup() {
    local file_path="$1"
    local ttl_seconds="$2"

    # Delay deletion so clipboard file-URI pastes can still read the temp file.
    nohup bash -c 'sleep "$1"; rm -f -- "$2"' _ "$ttl_seconds" "$file_path" >/dev/null 2>&1 &
}

copy_clip_path() {
    local file_path="$1"
    local file_uri="file://$file_path"

    if command -v wl-copy >/dev/null 2>&1; then
        printf '%s\n' "$file_uri" | wl-copy --type text/uri-list
        return 0
    fi

    if command -v xclip >/dev/null 2>&1; then
        printf '%s\n' "$file_uri" | xclip -selection clipboard -t text/uri-list
        return 0
    fi

    return 1
}

for cmd in wf-recorder slurp notify-send; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Missing dependency: $cmd" >&2
        notify-send "Screen Recorder" "Missing dependency: $cmd" -i dialog-error || true
        exit 1
    fi
done

if pgrep -x wf-recorder >/dev/null 2>&1; then
    # Stop current recording.
    pkill -INT -x wf-recorder || true

    if [[ -f "$STATE_FILE" ]]; then
        STATE_CONTENT=$(cat "$STATE_FILE")

        TAB_COUNT=$(grep -o $'\t' <<< "$STATE_CONTENT" | wc -l | tr -d ' ')
        if [[ "$TAB_COUNT" -ge 2 ]]; then
            RECORD_MODE=${STATE_CONTENT%%$'\t'*}
            REMAINDER=${STATE_CONTENT#*$'\t'}
            RECORD_FORMAT=${REMAINDER%%$'\t'*}
            LAST_FILE=${REMAINDER#*$'\t'}
        elif [[ "$STATE_CONTENT" == *$'\t'* ]]; then
            # Backward compatibility with previous state format: mode + path.
            RECORD_MODE=${STATE_CONTENT%%$'\t'*}
            LAST_FILE=${STATE_CONTENT#*$'\t'}
            RECORD_FORMAT="gif"
        else
            # Backward compatibility with old state format that stored only file path.
            RECORD_MODE="clipboard"
            RECORD_FORMAT="gif"
            LAST_FILE="$STATE_CONTENT"
        fi

        if [[ "$RECORD_MODE" == "save" ]]; then
            if copy_clip_path "$LAST_FILE"; then
                notify-send "Screen Recorder" "Saved clip and copied file reference: $(basename "$LAST_FILE")" -i video-x-generic
            else
                notify-send "Screen Recorder" "Saved clip: $(basename "$LAST_FILE")" -i video-x-generic
            fi
        else
            if [[ "$RECORD_FORMAT" == "gif" ]]; then
                GIF_FILE="${LAST_FILE%.*}.gif"

                if command -v ffmpeg >/dev/null 2>&1 && convert_mp4_to_gif "$LAST_FILE" "$GIF_FILE"; then
                    rm -f "$LAST_FILE"

                    if copy_clip_path "$GIF_FILE"; then
                        # Keep this workflow paste-ready while avoiding accumulated saved files.
                        schedule_cleanup "$GIF_FILE" "$CLEANUP_AFTER_SECONDS"
                        notify-send "Screen Recorder" "Copied GIF reference to clipboard (temp auto-delete in ${CLEANUP_AFTER_SECONDS}s)" -i video-x-generic
                    elif copy_clip_gif "$GIF_FILE"; then
                        rm -f "$GIF_FILE"
                        notify-send "Screen Recorder" "Copied GIF bytes to clipboard (temporary file removed)" -i video-x-generic
                    else
                        FALLBACK_FILE="$SAVE_DIR/$(basename "$GIF_FILE")"
                        mv "$GIF_FILE" "$FALLBACK_FILE"
                        notify-send "Screen Recorder" "Clipboard copy failed; GIF kept at $(basename "$FALLBACK_FILE")" -i video-x-generic
                    fi
                elif copy_clip_path "$LAST_FILE"; then
                    schedule_cleanup "$LAST_FILE" "$CLEANUP_AFTER_SECONDS"
                    notify-send "Screen Recorder" "GIF conversion failed, copied MP4 reference (temp auto-delete in ${CLEANUP_AFTER_SECONDS}s)" -i video-x-generic
                elif copy_clip_video "$LAST_FILE"; then
                    rm -f "$LAST_FILE"
                    notify-send "Screen Recorder" "GIF conversion failed, copied MP4 bytes (temporary file removed)" -i video-x-generic
                else
                    FALLBACK_FILE="$SAVE_DIR/$(basename "$LAST_FILE")"
                    mv "$LAST_FILE" "$FALLBACK_FILE"
                    notify-send "Screen Recorder" "Clipboard copy failed; MP4 kept at $(basename "$FALLBACK_FILE")" -i video-x-generic
                fi
            else
                if copy_clip_path "$LAST_FILE"; then
                    schedule_cleanup "$LAST_FILE" "$CLEANUP_AFTER_SECONDS"
                    notify-send "Screen Recorder" "Copied MP4 reference to clipboard (temp auto-delete in ${CLEANUP_AFTER_SECONDS}s)" -i video-x-generic
                elif copy_clip_video "$LAST_FILE"; then
                    rm -f "$LAST_FILE"
                    notify-send "Screen Recorder" "Copied MP4 bytes to clipboard (temporary file removed)" -i video-x-generic
                else
                    FALLBACK_FILE="$SAVE_DIR/$(basename "$LAST_FILE")"
                    mv "$LAST_FILE" "$FALLBACK_FILE"
                    notify-send "Screen Recorder" "Clipboard copy failed; MP4 kept at $(basename "$FALLBACK_FILE")" -i video-x-generic
                fi
            fi
        fi
        rm -f "$STATE_FILE"
    else
        notify-send "Screen Recorder" "Recording stopped" -i video-x-generic
    fi
    exit 0
fi

GEOMETRY=$(slurp -b 000000a0 -c 00aaffff -w 2)
if [[ -z "$GEOMETRY" ]]; then
    exit 0
fi

TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
if [[ "$MODE" == "save" ]]; then
    OUTPUT_FILE="$SAVE_DIR/snippet_$TIMESTAMP.mp4"
else
    OUTPUT_FILE="$TMP_DIR/snippet_$TIMESTAMP.mp4"
fi
printf '%s\t%s\t%s\n' "$MODE" "$CLIPBOARD_FORMAT" "$OUTPUT_FILE" > "$STATE_FILE"

notify-send "Screen Recorder" "Recording started" -i video-x-generic

# Run detached so keybind can trigger this script again to stop recording.
nohup wf-recorder -g "$GEOMETRY" -f "$OUTPUT_FILE" >/dev/null 2>&1 &