#!/usr/bin/env bash
set -euo pipefail

# AUTO-GENERATED by GitHub Copilot
# Purpose: Toggle region recording on Omarchy/Hyprland using one script for start/stop.
# Output: $HOME/repos/delulu-smash/local/assets/snippets/snippet_<timestamp>.mp4
# Usage: Bind this script to a key (for example SUPER+F10) and press again to stop.
# Requires: wf-recorder, slurp, notify-send, and wl-copy (or xclip fallback).
REPO_ROOT="$HOME/repos/delulu-smash"
SAVE_DIR="$REPO_ROOT/local/assets/snippets"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/screenrecord"
STATE_FILE="$STATE_DIR/current_recording.txt"

mkdir -p "$SAVE_DIR" "$STATE_DIR"

copy_clip_path() {
    local file_path="$1"
    local file_uri="file://$file_path"

    if command -v wl-copy >/dev/null 2>&1; then
        # Discord and other apps are more likely to accept URI-list clipboard for files.
        printf '%s\n' "$file_uri" | wl-copy --type text/uri-list
        return 0
    fi

    if command -v xclip >/dev/null 2>&1; then
        printf '%s\n' "$file_uri" | xclip -selection clipboard -t text/uri-list
        return 0
    fi

    return 1
}

for cmd in wf-recorder slurp notify-send; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Missing dependency: $cmd" >&2
        notify-send "Screen Recorder" "Missing dependency: $cmd" -i dialog-error || true
        exit 1
    fi
done

if pgrep -x wf-recorder >/dev/null 2>&1; then
    # Stop current recording.
    pkill -INT -x wf-recorder || true

    if [[ -f "$STATE_FILE" ]]; then
        LAST_FILE=$(cat "$STATE_FILE")
        if copy_clip_path "$LAST_FILE"; then
            notify-send "Screen Recorder" "Saved and copied to clipboard: $(basename "$LAST_FILE")" -i video-x-generic
        else
            notify-send "Screen Recorder" "Saved: $(basename "$LAST_FILE") (install wl-clipboard for copy support)" -i video-x-generic
        fi
        rm -f "$STATE_FILE"
    else
        notify-send "Screen Recorder" "Recording stopped" -i video-x-generic
    fi
    exit 0
fi

GEOMETRY=$(slurp -b 000000a0 -c 00aaffff -w 2)
if [[ -z "$GEOMETRY" ]]; then
    exit 0
fi

TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
OUTPUT_FILE="$SAVE_DIR/snippet_$TIMESTAMP.mp4"
printf '%s\n' "$OUTPUT_FILE" > "$STATE_FILE"

notify-send "Screen Recorder" "Recording started" -i video-x-generic

# Run detached so keybind can trigger this script again to stop recording.
nohup wf-recorder -g "$GEOMETRY" -f "$OUTPUT_FILE" >/dev/null 2>&1 &