# ---------------------------------------------------------------------------
# AUTO-GENERATED by Claude Code
# Purpose: offline tests for ds.ai.supermajor tools (network calls patched out).
# Usage: uv run pytest tests/ds/ai
# ---------------------------------------------------------------------------
from __future__ import annotations

import pytest
from ds.ai import supermajor
from ds.data.raw.supermajor import PlayerMatch
from pydantic_ai import ModelRetry


def test_find_players_caps_results(monkeypatch: pytest.MonkeyPatch) -> None:
    many = [PlayerMatch(player_id=f"S{1000 + i}", tag="Luke") for i in range(40)]
    monkeypatch.setattr(supermajor, "search_players", lambda _tag: many)
    assert len(supermajor.find_players("Luke")) == supermajor.MAX_PLAYERS


def test_get_player_usage_maps_period(monkeypatch: pytest.MonkeyPatch) -> None:
    calls = []
    monkeypatch.setattr(supermajor, "player_usage", lambda player, period: calls.append((player, period)))
    supermajor.get_player_usage("S4734338", "all_time")
    assert calls == [("S4734338", "All Time")]


def test_unknown_tag_asks_model_to_retry(monkeypatch: pytest.MonkeyPatch) -> None:
    def no_player(player: str, _period: str) -> None:
        raise ValueError(f"no supermajor.gg player tagged {player!r}; similar tags: none")

    monkeypatch.setattr(supermajor, "player_usage", no_player)
    with pytest.raises(ModelRetry, match="find_players"):
        supermajor.get_player_usage("NoSuchTag")
